/* CMESOAPH.h
   Generated by gSOAP 2.7.10 from CMESOAPService.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef CMESOAPH_H
#define CMESOAPH_H
#include "CMESOAPStub.h"

namespace CMESOAP {
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_byte
#define SOAP_TYPE_CMESOAP_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_CMESOAP_int
#define SOAP_TYPE_CMESOAP_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_CMESOAP_LONG64
#define SOAP_TYPE_CMESOAP_LONG64 (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_CMESOAP_std__string
#define SOAP_TYPE_CMESOAP_std__string (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_SOAP_ENV__Fault
#define SOAP_TYPE_CMESOAP_SOAP_ENV__Fault (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_SOAP_ENV__Reason
#define SOAP_TYPE_CMESOAP_SOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_SOAP_ENV__Detail
#define SOAP_TYPE_CMESOAP_SOAP_ENV__Detail (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_SOAP_ENV__Code
#define SOAP_TYPE_CMESOAP_SOAP_ENV__Code (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_SOAP_ENV__Header
#define SOAP_TYPE_CMESOAP_SOAP_ENV__Header (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_CMESOAP_ns1__deletableNotification
#define SOAP_TYPE_CMESOAP_ns1__deletableNotification (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__deletableNotification(struct soap*, struct ns1__deletableNotification *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__deletableNotification(struct soap*, const struct ns1__deletableNotification *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__deletableNotification(struct soap*, const struct ns1__deletableNotification *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__deletableNotification(struct soap*, const char*, int, const struct ns1__deletableNotification *, const char*);
SOAP_FMAC3 struct ns1__deletableNotification * SOAP_FMAC4 soap_get_ns1__deletableNotification(struct soap*, struct ns1__deletableNotification *, const char*, const char*);
SOAP_FMAC3 struct ns1__deletableNotification * SOAP_FMAC4 soap_in_ns1__deletableNotification(struct soap*, const char*, struct ns1__deletableNotification *, const char*);
SOAP_FMAC5 struct ns1__deletableNotification * SOAP_FMAC6 soap_new_ns1__deletableNotification(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__deletableNotification(struct soap*, struct ns1__deletableNotification*);
SOAP_FMAC3 struct ns1__deletableNotification * SOAP_FMAC4 soap_instantiate_ns1__deletableNotification(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__deletableNotification(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_ns1__deletableNotificationResponse
#define SOAP_TYPE_CMESOAP_ns1__deletableNotificationResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__deletableNotificationResponse(struct soap*, struct ns1__deletableNotificationResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__deletableNotificationResponse(struct soap*, const struct ns1__deletableNotificationResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__deletableNotificationResponse(struct soap*, const struct ns1__deletableNotificationResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__deletableNotificationResponse(struct soap*, const char*, int, const struct ns1__deletableNotificationResponse *, const char*);
SOAP_FMAC3 struct ns1__deletableNotificationResponse * SOAP_FMAC4 soap_get_ns1__deletableNotificationResponse(struct soap*, struct ns1__deletableNotificationResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__deletableNotificationResponse * SOAP_FMAC4 soap_in_ns1__deletableNotificationResponse(struct soap*, const char*, struct ns1__deletableNotificationResponse *, const char*);
SOAP_FMAC5 struct ns1__deletableNotificationResponse * SOAP_FMAC6 soap_new_ns1__deletableNotificationResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__deletableNotificationResponse(struct soap*, struct ns1__deletableNotificationResponse*);
SOAP_FMAC3 struct ns1__deletableNotificationResponse * SOAP_FMAC4 soap_instantiate_ns1__deletableNotificationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__deletableNotificationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_ns1__importNotification
#define SOAP_TYPE_CMESOAP_ns1__importNotification (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__importNotification(struct soap*, struct ns1__importNotification *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__importNotification(struct soap*, const struct ns1__importNotification *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__importNotification(struct soap*, const struct ns1__importNotification *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__importNotification(struct soap*, const char*, int, const struct ns1__importNotification *, const char*);
SOAP_FMAC3 struct ns1__importNotification * SOAP_FMAC4 soap_get_ns1__importNotification(struct soap*, struct ns1__importNotification *, const char*, const char*);
SOAP_FMAC3 struct ns1__importNotification * SOAP_FMAC4 soap_in_ns1__importNotification(struct soap*, const char*, struct ns1__importNotification *, const char*);
SOAP_FMAC5 struct ns1__importNotification * SOAP_FMAC6 soap_new_ns1__importNotification(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__importNotification(struct soap*, struct ns1__importNotification*);
SOAP_FMAC3 struct ns1__importNotification * SOAP_FMAC4 soap_instantiate_ns1__importNotification(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__importNotification(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_ns1__importNotificationResponse
#define SOAP_TYPE_CMESOAP_ns1__importNotificationResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__importNotificationResponse(struct soap*, struct ns1__importNotificationResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__importNotificationResponse(struct soap*, const struct ns1__importNotificationResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__importNotificationResponse(struct soap*, const struct ns1__importNotificationResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__importNotificationResponse(struct soap*, const char*, int, const struct ns1__importNotificationResponse *, const char*);
SOAP_FMAC3 struct ns1__importNotificationResponse * SOAP_FMAC4 soap_get_ns1__importNotificationResponse(struct soap*, struct ns1__importNotificationResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__importNotificationResponse * SOAP_FMAC4 soap_in_ns1__importNotificationResponse(struct soap*, const char*, struct ns1__importNotificationResponse *, const char*);
SOAP_FMAC5 struct ns1__importNotificationResponse * SOAP_FMAC6 soap_new_ns1__importNotificationResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__importNotificationResponse(struct soap*, struct ns1__importNotificationResponse*);
SOAP_FMAC3 struct ns1__importNotificationResponse * SOAP_FMAC4 soap_instantiate_ns1__importNotificationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__importNotificationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_ns1__sessionNotification
#define SOAP_TYPE_CMESOAP_ns1__sessionNotification (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sessionNotification(struct soap*, struct ns1__sessionNotification *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sessionNotification(struct soap*, const struct ns1__sessionNotification *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sessionNotification(struct soap*, const struct ns1__sessionNotification *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sessionNotification(struct soap*, const char*, int, const struct ns1__sessionNotification *, const char*);
SOAP_FMAC3 struct ns1__sessionNotification * SOAP_FMAC4 soap_get_ns1__sessionNotification(struct soap*, struct ns1__sessionNotification *, const char*, const char*);
SOAP_FMAC3 struct ns1__sessionNotification * SOAP_FMAC4 soap_in_ns1__sessionNotification(struct soap*, const char*, struct ns1__sessionNotification *, const char*);
SOAP_FMAC5 struct ns1__sessionNotification * SOAP_FMAC6 soap_new_ns1__sessionNotification(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sessionNotification(struct soap*, struct ns1__sessionNotification*);
SOAP_FMAC3 struct ns1__sessionNotification * SOAP_FMAC4 soap_instantiate_ns1__sessionNotification(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sessionNotification(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_ns1__sessionNotificationResponse
#define SOAP_TYPE_CMESOAP_ns1__sessionNotificationResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sessionNotificationResponse(struct soap*, struct ns1__sessionNotificationResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sessionNotificationResponse(struct soap*, const struct ns1__sessionNotificationResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sessionNotificationResponse(struct soap*, const struct ns1__sessionNotificationResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sessionNotificationResponse(struct soap*, const char*, int, const struct ns1__sessionNotificationResponse *, const char*);
SOAP_FMAC3 struct ns1__sessionNotificationResponse * SOAP_FMAC4 soap_get_ns1__sessionNotificationResponse(struct soap*, struct ns1__sessionNotificationResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__sessionNotificationResponse * SOAP_FMAC4 soap_in_ns1__sessionNotificationResponse(struct soap*, const char*, struct ns1__sessionNotificationResponse *, const char*);
SOAP_FMAC5 struct ns1__sessionNotificationResponse * SOAP_FMAC6 soap_new_ns1__sessionNotificationResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sessionNotificationResponse(struct soap*, struct ns1__sessionNotificationResponse*);
SOAP_FMAC3 struct ns1__sessionNotificationResponse * SOAP_FMAC4 soap_instantiate_ns1__sessionNotificationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sessionNotificationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_ns1__cacheNotification
#define SOAP_TYPE_CMESOAP_ns1__cacheNotification (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__cacheNotification(struct soap*, struct ns1__cacheNotification *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__cacheNotification(struct soap*, const struct ns1__cacheNotification *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__cacheNotification(struct soap*, const struct ns1__cacheNotification *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__cacheNotification(struct soap*, const char*, int, const struct ns1__cacheNotification *, const char*);
SOAP_FMAC3 struct ns1__cacheNotification * SOAP_FMAC4 soap_get_ns1__cacheNotification(struct soap*, struct ns1__cacheNotification *, const char*, const char*);
SOAP_FMAC3 struct ns1__cacheNotification * SOAP_FMAC4 soap_in_ns1__cacheNotification(struct soap*, const char*, struct ns1__cacheNotification *, const char*);
SOAP_FMAC5 struct ns1__cacheNotification * SOAP_FMAC6 soap_new_ns1__cacheNotification(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__cacheNotification(struct soap*, struct ns1__cacheNotification*);
SOAP_FMAC3 struct ns1__cacheNotification * SOAP_FMAC4 soap_instantiate_ns1__cacheNotification(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__cacheNotification(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CMESOAP_ns1__cacheNotificationResponse
#define SOAP_TYPE_CMESOAP_ns1__cacheNotificationResponse (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__cacheNotificationResponse(struct soap*, struct ns1__cacheNotificationResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__cacheNotificationResponse(struct soap*, const struct ns1__cacheNotificationResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__cacheNotificationResponse(struct soap*, const struct ns1__cacheNotificationResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__cacheNotificationResponse(struct soap*, const char*, int, const struct ns1__cacheNotificationResponse *, const char*);
SOAP_FMAC3 struct ns1__cacheNotificationResponse * SOAP_FMAC4 soap_get_ns1__cacheNotificationResponse(struct soap*, struct ns1__cacheNotificationResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__cacheNotificationResponse * SOAP_FMAC4 soap_in_ns1__cacheNotificationResponse(struct soap*, const char*, struct ns1__cacheNotificationResponse *, const char*);
SOAP_FMAC5 struct ns1__cacheNotificationResponse * SOAP_FMAC6 soap_new_ns1__cacheNotificationResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__cacheNotificationResponse(struct soap*, struct ns1__cacheNotificationResponse*);
SOAP_FMAC3 struct ns1__cacheNotificationResponse * SOAP_FMAC4 soap_instantiate_ns1__cacheNotificationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__cacheNotificationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_CMESOAP_PointerToSOAP_ENV__Reason (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_CMESOAP_PointerToSOAP_ENV__Detail (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_CMESOAP_PointerToSOAP_ENV__Code
#define SOAP_TYPE_CMESOAP_PointerToSOAP_ENV__Code (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_CMESOAP__QName
#define SOAP_TYPE_CMESOAP__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_CMESOAP_string
#define SOAP_TYPE_CMESOAP_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

} // namespace CMESOAP


#endif

/* End of CMESOAPH.h */
