/* LAMFacadeForCMEH.h
   Generated by gSOAP 2.7.10 from LAMFacadeForCME.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef LAMFacadeForCMEH_H
#define LAMFacadeForCMEH_H
#include "LAMFacadeForCMEStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ClusterList
#define SOAP_TYPE_ns1__ClusterList (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ClusterList(struct soap*, const char*, int, const ns1__ClusterList *, const char*);
SOAP_FMAC3 ns1__ClusterList * SOAP_FMAC4 soap_get_ns1__ClusterList(struct soap*, ns1__ClusterList *, const char*, const char*);
SOAP_FMAC3 ns1__ClusterList * SOAP_FMAC4 soap_in_ns1__ClusterList(struct soap*, const char*, ns1__ClusterList *, const char*);
SOAP_FMAC5 ns1__ClusterList * SOAP_FMAC6 soap_new_ns1__ClusterList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ClusterList(struct soap*, ns1__ClusterList*);
SOAP_FMAC3 ns1__ClusterList * SOAP_FMAC4 soap_instantiate_ns1__ClusterList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ClusterList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__Cluster
#define SOAP_TYPE_ns1__Cluster (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Cluster(struct soap*, const char*, int, const ns1__Cluster *, const char*);
SOAP_FMAC3 ns1__Cluster * SOAP_FMAC4 soap_get_ns1__Cluster(struct soap*, ns1__Cluster *, const char*, const char*);
SOAP_FMAC3 ns1__Cluster * SOAP_FMAC4 soap_in_ns1__Cluster(struct soap*, const char*, ns1__Cluster *, const char*);
SOAP_FMAC5 ns1__Cluster * SOAP_FMAC6 soap_new_ns1__Cluster(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__Cluster(struct soap*, ns1__Cluster*);
SOAP_FMAC3 ns1__Cluster * SOAP_FMAC4 soap_instantiate_ns1__Cluster(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Cluster(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ProviderList
#define SOAP_TYPE_ns1__ProviderList (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ProviderList(struct soap*, const char*, int, const ns1__ProviderList *, const char*);
SOAP_FMAC3 ns1__ProviderList * SOAP_FMAC4 soap_get_ns1__ProviderList(struct soap*, ns1__ProviderList *, const char*, const char*);
SOAP_FMAC3 ns1__ProviderList * SOAP_FMAC4 soap_in_ns1__ProviderList(struct soap*, const char*, ns1__ProviderList *, const char*);
SOAP_FMAC5 ns1__ProviderList * SOAP_FMAC6 soap_new_ns1__ProviderList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ProviderList(struct soap*, ns1__ProviderList*);
SOAP_FMAC3 ns1__ProviderList * SOAP_FMAC4 soap_instantiate_ns1__ProviderList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ProviderList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__Asset
#define SOAP_TYPE_ns1__Asset (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Asset(struct soap*, const char*, int, const ns1__Asset *, const char*);
SOAP_FMAC3 ns1__Asset * SOAP_FMAC4 soap_get_ns1__Asset(struct soap*, ns1__Asset *, const char*, const char*);
SOAP_FMAC3 ns1__Asset * SOAP_FMAC4 soap_in_ns1__Asset(struct soap*, const char*, ns1__Asset *, const char*);
SOAP_FMAC5 ns1__Asset * SOAP_FMAC6 soap_new_ns1__Asset(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__Asset(struct soap*, ns1__Asset*);
SOAP_FMAC3 ns1__Asset * SOAP_FMAC4 soap_instantiate_ns1__Asset(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Asset(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__AssetList
#define SOAP_TYPE_ns1__AssetList (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AssetList(struct soap*, const char*, int, const ns1__AssetList *, const char*);
SOAP_FMAC3 ns1__AssetList * SOAP_FMAC4 soap_get_ns1__AssetList(struct soap*, ns1__AssetList *, const char*, const char*);
SOAP_FMAC3 ns1__AssetList * SOAP_FMAC4 soap_in_ns1__AssetList(struct soap*, const char*, ns1__AssetList *, const char*);
SOAP_FMAC5 ns1__AssetList * SOAP_FMAC6 soap_new_ns1__AssetList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__AssetList(struct soap*, ns1__AssetList*);
SOAP_FMAC3 ns1__AssetList * SOAP_FMAC4 soap_instantiate_ns1__AssetList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__AssetList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns2__copyFrom
#define SOAP_TYPE_ns2__copyFrom (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__copyFrom(struct soap*, struct ns2__copyFrom *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__copyFrom(struct soap*, const struct ns2__copyFrom *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__copyFrom(struct soap*, const struct ns2__copyFrom *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__copyFrom(struct soap*, const char*, int, const struct ns2__copyFrom *, const char*);
SOAP_FMAC3 struct ns2__copyFrom * SOAP_FMAC4 soap_get_ns2__copyFrom(struct soap*, struct ns2__copyFrom *, const char*, const char*);
SOAP_FMAC3 struct ns2__copyFrom * SOAP_FMAC4 soap_in_ns2__copyFrom(struct soap*, const char*, struct ns2__copyFrom *, const char*);
SOAP_FMAC5 struct ns2__copyFrom * SOAP_FMAC6 soap_new_ns2__copyFrom(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__copyFrom(struct soap*, struct ns2__copyFrom*);
SOAP_FMAC3 struct ns2__copyFrom * SOAP_FMAC4 soap_instantiate_ns2__copyFrom(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__copyFrom(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__copyFromResponse
#define SOAP_TYPE_ns2__copyFromResponse (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__copyFromResponse(struct soap*, struct ns2__copyFromResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__copyFromResponse(struct soap*, const struct ns2__copyFromResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__copyFromResponse(struct soap*, const struct ns2__copyFromResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__copyFromResponse(struct soap*, const char*, int, const struct ns2__copyFromResponse *, const char*);
SOAP_FMAC3 struct ns2__copyFromResponse * SOAP_FMAC4 soap_get_ns2__copyFromResponse(struct soap*, struct ns2__copyFromResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__copyFromResponse * SOAP_FMAC4 soap_in_ns2__copyFromResponse(struct soap*, const char*, struct ns2__copyFromResponse *, const char*);
SOAP_FMAC5 struct ns2__copyFromResponse * SOAP_FMAC6 soap_new_ns2__copyFromResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__copyFromResponse(struct soap*, struct ns2__copyFromResponse*);
SOAP_FMAC3 struct ns2__copyFromResponse * SOAP_FMAC4 soap_instantiate_ns2__copyFromResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__copyFromResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__getExportURL
#define SOAP_TYPE_ns2__getExportURL (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getExportURL(struct soap*, struct ns2__getExportURL *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getExportURL(struct soap*, const struct ns2__getExportURL *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getExportURL(struct soap*, const struct ns2__getExportURL *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getExportURL(struct soap*, const char*, int, const struct ns2__getExportURL *, const char*);
SOAP_FMAC3 struct ns2__getExportURL * SOAP_FMAC4 soap_get_ns2__getExportURL(struct soap*, struct ns2__getExportURL *, const char*, const char*);
SOAP_FMAC3 struct ns2__getExportURL * SOAP_FMAC4 soap_in_ns2__getExportURL(struct soap*, const char*, struct ns2__getExportURL *, const char*);
SOAP_FMAC5 struct ns2__getExportURL * SOAP_FMAC6 soap_new_ns2__getExportURL(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__getExportURL(struct soap*, struct ns2__getExportURL*);
SOAP_FMAC3 struct ns2__getExportURL * SOAP_FMAC4 soap_instantiate_ns2__getExportURL(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__getExportURL(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__getExportURLResponse
#define SOAP_TYPE_ns2__getExportURLResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getExportURLResponse(struct soap*, struct ns2__getExportURLResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getExportURLResponse(struct soap*, const struct ns2__getExportURLResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getExportURLResponse(struct soap*, const struct ns2__getExportURLResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getExportURLResponse(struct soap*, const char*, int, const struct ns2__getExportURLResponse *, const char*);
SOAP_FMAC3 struct ns2__getExportURLResponse * SOAP_FMAC4 soap_get_ns2__getExportURLResponse(struct soap*, struct ns2__getExportURLResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getExportURLResponse * SOAP_FMAC4 soap_in_ns2__getExportURLResponse(struct soap*, const char*, struct ns2__getExportURLResponse *, const char*);
SOAP_FMAC5 struct ns2__getExportURLResponse * SOAP_FMAC6 soap_new_ns2__getExportURLResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__getExportURLResponse(struct soap*, struct ns2__getExportURLResponse*);
SOAP_FMAC3 struct ns2__getExportURLResponse * SOAP_FMAC4 soap_instantiate_ns2__getExportURLResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__getExportURLResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__listCluster
#define SOAP_TYPE_ns2__listCluster (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__listCluster(struct soap*, struct ns2__listCluster *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__listCluster(struct soap*, const struct ns2__listCluster *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__listCluster(struct soap*, const struct ns2__listCluster *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__listCluster(struct soap*, const char*, int, const struct ns2__listCluster *, const char*);
SOAP_FMAC3 struct ns2__listCluster * SOAP_FMAC4 soap_get_ns2__listCluster(struct soap*, struct ns2__listCluster *, const char*, const char*);
SOAP_FMAC3 struct ns2__listCluster * SOAP_FMAC4 soap_in_ns2__listCluster(struct soap*, const char*, struct ns2__listCluster *, const char*);
SOAP_FMAC5 struct ns2__listCluster * SOAP_FMAC6 soap_new_ns2__listCluster(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__listCluster(struct soap*, struct ns2__listCluster*);
SOAP_FMAC3 struct ns2__listCluster * SOAP_FMAC4 soap_instantiate_ns2__listCluster(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__listCluster(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__listClusterResponse
#define SOAP_TYPE_ns2__listClusterResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__listClusterResponse(struct soap*, struct ns2__listClusterResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__listClusterResponse(struct soap*, const struct ns2__listClusterResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__listClusterResponse(struct soap*, const struct ns2__listClusterResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__listClusterResponse(struct soap*, const char*, int, const struct ns2__listClusterResponse *, const char*);
SOAP_FMAC3 struct ns2__listClusterResponse * SOAP_FMAC4 soap_get_ns2__listClusterResponse(struct soap*, struct ns2__listClusterResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__listClusterResponse * SOAP_FMAC4 soap_in_ns2__listClusterResponse(struct soap*, const char*, struct ns2__listClusterResponse *, const char*);
SOAP_FMAC5 struct ns2__listClusterResponse * SOAP_FMAC6 soap_new_ns2__listClusterResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__listClusterResponse(struct soap*, struct ns2__listClusterResponse*);
SOAP_FMAC3 struct ns2__listClusterResponse * SOAP_FMAC4 soap_instantiate_ns2__listClusterResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__listClusterResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__handshake
#define SOAP_TYPE_ns2__handshake (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__handshake(struct soap*, struct ns2__handshake *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__handshake(struct soap*, const struct ns2__handshake *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__handshake(struct soap*, const struct ns2__handshake *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__handshake(struct soap*, const char*, int, const struct ns2__handshake *, const char*);
SOAP_FMAC3 struct ns2__handshake * SOAP_FMAC4 soap_get_ns2__handshake(struct soap*, struct ns2__handshake *, const char*, const char*);
SOAP_FMAC3 struct ns2__handshake * SOAP_FMAC4 soap_in_ns2__handshake(struct soap*, const char*, struct ns2__handshake *, const char*);
SOAP_FMAC5 struct ns2__handshake * SOAP_FMAC6 soap_new_ns2__handshake(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__handshake(struct soap*, struct ns2__handshake*);
SOAP_FMAC3 struct ns2__handshake * SOAP_FMAC4 soap_instantiate_ns2__handshake(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__handshake(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__handshakeResponse
#define SOAP_TYPE_ns2__handshakeResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__handshakeResponse(struct soap*, struct ns2__handshakeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__handshakeResponse(struct soap*, const struct ns2__handshakeResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__handshakeResponse(struct soap*, const struct ns2__handshakeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__handshakeResponse(struct soap*, const char*, int, const struct ns2__handshakeResponse *, const char*);
SOAP_FMAC3 struct ns2__handshakeResponse * SOAP_FMAC4 soap_get_ns2__handshakeResponse(struct soap*, struct ns2__handshakeResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__handshakeResponse * SOAP_FMAC4 soap_in_ns2__handshakeResponse(struct soap*, const char*, struct ns2__handshakeResponse *, const char*);
SOAP_FMAC5 struct ns2__handshakeResponse * SOAP_FMAC6 soap_new_ns2__handshakeResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__handshakeResponse(struct soap*, struct ns2__handshakeResponse*);
SOAP_FMAC3 struct ns2__handshakeResponse * SOAP_FMAC4 soap_instantiate_ns2__handshakeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__handshakeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__getClusterConfig
#define SOAP_TYPE_ns2__getClusterConfig (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getClusterConfig(struct soap*, struct ns2__getClusterConfig *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getClusterConfig(struct soap*, const struct ns2__getClusterConfig *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getClusterConfig(struct soap*, const struct ns2__getClusterConfig *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getClusterConfig(struct soap*, const char*, int, const struct ns2__getClusterConfig *, const char*);
SOAP_FMAC3 struct ns2__getClusterConfig * SOAP_FMAC4 soap_get_ns2__getClusterConfig(struct soap*, struct ns2__getClusterConfig *, const char*, const char*);
SOAP_FMAC3 struct ns2__getClusterConfig * SOAP_FMAC4 soap_in_ns2__getClusterConfig(struct soap*, const char*, struct ns2__getClusterConfig *, const char*);
SOAP_FMAC5 struct ns2__getClusterConfig * SOAP_FMAC6 soap_new_ns2__getClusterConfig(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__getClusterConfig(struct soap*, struct ns2__getClusterConfig*);
SOAP_FMAC3 struct ns2__getClusterConfig * SOAP_FMAC4 soap_instantiate_ns2__getClusterConfig(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__getClusterConfig(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__getClusterConfigResponse
#define SOAP_TYPE_ns2__getClusterConfigResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getClusterConfigResponse(struct soap*, struct ns2__getClusterConfigResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getClusterConfigResponse(struct soap*, const struct ns2__getClusterConfigResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getClusterConfigResponse(struct soap*, const struct ns2__getClusterConfigResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getClusterConfigResponse(struct soap*, const char*, int, const struct ns2__getClusterConfigResponse *, const char*);
SOAP_FMAC3 struct ns2__getClusterConfigResponse * SOAP_FMAC4 soap_get_ns2__getClusterConfigResponse(struct soap*, struct ns2__getClusterConfigResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getClusterConfigResponse * SOAP_FMAC4 soap_in_ns2__getClusterConfigResponse(struct soap*, const char*, struct ns2__getClusterConfigResponse *, const char*);
SOAP_FMAC5 struct ns2__getClusterConfigResponse * SOAP_FMAC6 soap_new_ns2__getClusterConfigResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__getClusterConfigResponse(struct soap*, struct ns2__getClusterConfigResponse*);
SOAP_FMAC3 struct ns2__getClusterConfigResponse * SOAP_FMAC4 soap_instantiate_ns2__getClusterConfigResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__getClusterConfigResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__listProvider
#define SOAP_TYPE_ns2__listProvider (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__listProvider(struct soap*, struct ns2__listProvider *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__listProvider(struct soap*, const struct ns2__listProvider *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__listProvider(struct soap*, const struct ns2__listProvider *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__listProvider(struct soap*, const char*, int, const struct ns2__listProvider *, const char*);
SOAP_FMAC3 struct ns2__listProvider * SOAP_FMAC4 soap_get_ns2__listProvider(struct soap*, struct ns2__listProvider *, const char*, const char*);
SOAP_FMAC3 struct ns2__listProvider * SOAP_FMAC4 soap_in_ns2__listProvider(struct soap*, const char*, struct ns2__listProvider *, const char*);
SOAP_FMAC5 struct ns2__listProvider * SOAP_FMAC6 soap_new_ns2__listProvider(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__listProvider(struct soap*, struct ns2__listProvider*);
SOAP_FMAC3 struct ns2__listProvider * SOAP_FMAC4 soap_instantiate_ns2__listProvider(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__listProvider(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__listProviderResponse
#define SOAP_TYPE_ns2__listProviderResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__listProviderResponse(struct soap*, struct ns2__listProviderResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__listProviderResponse(struct soap*, const struct ns2__listProviderResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__listProviderResponse(struct soap*, const struct ns2__listProviderResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__listProviderResponse(struct soap*, const char*, int, const struct ns2__listProviderResponse *, const char*);
SOAP_FMAC3 struct ns2__listProviderResponse * SOAP_FMAC4 soap_get_ns2__listProviderResponse(struct soap*, struct ns2__listProviderResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__listProviderResponse * SOAP_FMAC4 soap_in_ns2__listProviderResponse(struct soap*, const char*, struct ns2__listProviderResponse *, const char*);
SOAP_FMAC5 struct ns2__listProviderResponse * SOAP_FMAC6 soap_new_ns2__listProviderResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__listProviderResponse(struct soap*, struct ns2__listProviderResponse*);
SOAP_FMAC3 struct ns2__listProviderResponse * SOAP_FMAC4 soap_instantiate_ns2__listProviderResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__listProviderResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__listAsset
#define SOAP_TYPE_ns2__listAsset (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__listAsset(struct soap*, struct ns2__listAsset *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__listAsset(struct soap*, const struct ns2__listAsset *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__listAsset(struct soap*, const struct ns2__listAsset *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__listAsset(struct soap*, const char*, int, const struct ns2__listAsset *, const char*);
SOAP_FMAC3 struct ns2__listAsset * SOAP_FMAC4 soap_get_ns2__listAsset(struct soap*, struct ns2__listAsset *, const char*, const char*);
SOAP_FMAC3 struct ns2__listAsset * SOAP_FMAC4 soap_in_ns2__listAsset(struct soap*, const char*, struct ns2__listAsset *, const char*);
SOAP_FMAC5 struct ns2__listAsset * SOAP_FMAC6 soap_new_ns2__listAsset(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__listAsset(struct soap*, struct ns2__listAsset*);
SOAP_FMAC3 struct ns2__listAsset * SOAP_FMAC4 soap_instantiate_ns2__listAsset(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__listAsset(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__listAssetResponse
#define SOAP_TYPE_ns2__listAssetResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__listAssetResponse(struct soap*, struct ns2__listAssetResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__listAssetResponse(struct soap*, const struct ns2__listAssetResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__listAssetResponse(struct soap*, const struct ns2__listAssetResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__listAssetResponse(struct soap*, const char*, int, const struct ns2__listAssetResponse *, const char*);
SOAP_FMAC3 struct ns2__listAssetResponse * SOAP_FMAC4 soap_get_ns2__listAssetResponse(struct soap*, struct ns2__listAssetResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__listAssetResponse * SOAP_FMAC4 soap_in_ns2__listAssetResponse(struct soap*, const char*, struct ns2__listAssetResponse *, const char*);
SOAP_FMAC5 struct ns2__listAssetResponse * SOAP_FMAC6 soap_new_ns2__listAssetResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__listAssetResponse(struct soap*, struct ns2__listAssetResponse*);
SOAP_FMAC3 struct ns2__listAssetResponse * SOAP_FMAC4 soap_instantiate_ns2__listAssetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__listAssetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__getAsset
#define SOAP_TYPE_ns2__getAsset (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getAsset(struct soap*, struct ns2__getAsset *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getAsset(struct soap*, const struct ns2__getAsset *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getAsset(struct soap*, const struct ns2__getAsset *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getAsset(struct soap*, const char*, int, const struct ns2__getAsset *, const char*);
SOAP_FMAC3 struct ns2__getAsset * SOAP_FMAC4 soap_get_ns2__getAsset(struct soap*, struct ns2__getAsset *, const char*, const char*);
SOAP_FMAC3 struct ns2__getAsset * SOAP_FMAC4 soap_in_ns2__getAsset(struct soap*, const char*, struct ns2__getAsset *, const char*);
SOAP_FMAC5 struct ns2__getAsset * SOAP_FMAC6 soap_new_ns2__getAsset(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__getAsset(struct soap*, struct ns2__getAsset*);
SOAP_FMAC3 struct ns2__getAsset * SOAP_FMAC4 soap_instantiate_ns2__getAsset(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__getAsset(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__getAssetResponse
#define SOAP_TYPE_ns2__getAssetResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getAssetResponse(struct soap*, struct ns2__getAssetResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getAssetResponse(struct soap*, const struct ns2__getAssetResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getAssetResponse(struct soap*, const struct ns2__getAssetResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getAssetResponse(struct soap*, const char*, int, const struct ns2__getAssetResponse *, const char*);
SOAP_FMAC3 struct ns2__getAssetResponse * SOAP_FMAC4 soap_get_ns2__getAssetResponse(struct soap*, struct ns2__getAssetResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getAssetResponse * SOAP_FMAC4 soap_in_ns2__getAssetResponse(struct soap*, const char*, struct ns2__getAssetResponse *, const char*);
SOAP_FMAC5 struct ns2__getAssetResponse * SOAP_FMAC6 soap_new_ns2__getAssetResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__getAssetResponse(struct soap*, struct ns2__getAssetResponse*);
SOAP_FMAC3 struct ns2__getAssetResponse * SOAP_FMAC4 soap_instantiate_ns2__getAssetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__getAssetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__deleteCache
#define SOAP_TYPE_ns2__deleteCache (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__deleteCache(struct soap*, struct ns2__deleteCache *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__deleteCache(struct soap*, const struct ns2__deleteCache *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__deleteCache(struct soap*, const struct ns2__deleteCache *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__deleteCache(struct soap*, const char*, int, const struct ns2__deleteCache *, const char*);
SOAP_FMAC3 struct ns2__deleteCache * SOAP_FMAC4 soap_get_ns2__deleteCache(struct soap*, struct ns2__deleteCache *, const char*, const char*);
SOAP_FMAC3 struct ns2__deleteCache * SOAP_FMAC4 soap_in_ns2__deleteCache(struct soap*, const char*, struct ns2__deleteCache *, const char*);
SOAP_FMAC5 struct ns2__deleteCache * SOAP_FMAC6 soap_new_ns2__deleteCache(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__deleteCache(struct soap*, struct ns2__deleteCache*);
SOAP_FMAC3 struct ns2__deleteCache * SOAP_FMAC4 soap_instantiate_ns2__deleteCache(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__deleteCache(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__deleteCacheResponse
#define SOAP_TYPE_ns2__deleteCacheResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__deleteCacheResponse(struct soap*, struct ns2__deleteCacheResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__deleteCacheResponse(struct soap*, const struct ns2__deleteCacheResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__deleteCacheResponse(struct soap*, const struct ns2__deleteCacheResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__deleteCacheResponse(struct soap*, const char*, int, const struct ns2__deleteCacheResponse *, const char*);
SOAP_FMAC3 struct ns2__deleteCacheResponse * SOAP_FMAC4 soap_get_ns2__deleteCacheResponse(struct soap*, struct ns2__deleteCacheResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__deleteCacheResponse * SOAP_FMAC4 soap_in_ns2__deleteCacheResponse(struct soap*, const char*, struct ns2__deleteCacheResponse *, const char*);
SOAP_FMAC5 struct ns2__deleteCacheResponse * SOAP_FMAC6 soap_new_ns2__deleteCacheResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__deleteCacheResponse(struct soap*, struct ns2__deleteCacheResponse*);
SOAP_FMAC3 struct ns2__deleteCacheResponse * SOAP_FMAC4 soap_instantiate_ns2__deleteCacheResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__deleteCacheResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__addCache
#define SOAP_TYPE_ns2__addCache (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__addCache(struct soap*, struct ns2__addCache *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__addCache(struct soap*, const struct ns2__addCache *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__addCache(struct soap*, const struct ns2__addCache *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__addCache(struct soap*, const char*, int, const struct ns2__addCache *, const char*);
SOAP_FMAC3 struct ns2__addCache * SOAP_FMAC4 soap_get_ns2__addCache(struct soap*, struct ns2__addCache *, const char*, const char*);
SOAP_FMAC3 struct ns2__addCache * SOAP_FMAC4 soap_in_ns2__addCache(struct soap*, const char*, struct ns2__addCache *, const char*);
SOAP_FMAC5 struct ns2__addCache * SOAP_FMAC6 soap_new_ns2__addCache(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__addCache(struct soap*, struct ns2__addCache*);
SOAP_FMAC3 struct ns2__addCache * SOAP_FMAC4 soap_instantiate_ns2__addCache(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__addCache(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__addCacheResponse
#define SOAP_TYPE_ns2__addCacheResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__addCacheResponse(struct soap*, struct ns2__addCacheResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__addCacheResponse(struct soap*, const struct ns2__addCacheResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__addCacheResponse(struct soap*, const struct ns2__addCacheResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__addCacheResponse(struct soap*, const char*, int, const struct ns2__addCacheResponse *, const char*);
SOAP_FMAC3 struct ns2__addCacheResponse * SOAP_FMAC4 soap_get_ns2__addCacheResponse(struct soap*, struct ns2__addCacheResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__addCacheResponse * SOAP_FMAC4 soap_in_ns2__addCacheResponse(struct soap*, const char*, struct ns2__addCacheResponse *, const char*);
SOAP_FMAC5 struct ns2__addCacheResponse * SOAP_FMAC6 soap_new_ns2__addCacheResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__addCacheResponse(struct soap*, struct ns2__addCacheResponse*);
SOAP_FMAC3 struct ns2__addCacheResponse * SOAP_FMAC4 soap_instantiate_ns2__addCacheResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__addCacheResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__ClusterList
#define SOAP_TYPE_PointerTons1__ClusterList (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ClusterList(struct soap*, ns1__ClusterList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ClusterList(struct soap*, ns1__ClusterList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ClusterList(struct soap*, const char *, int, ns1__ClusterList *const*, const char *);
SOAP_FMAC3 ns1__ClusterList ** SOAP_FMAC4 soap_get_PointerTons1__ClusterList(struct soap*, ns1__ClusterList **, const char*, const char*);
SOAP_FMAC3 ns1__ClusterList ** SOAP_FMAC4 soap_in_PointerTons1__ClusterList(struct soap*, const char*, ns1__ClusterList **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ProviderList
#define SOAP_TYPE_PointerTons1__ProviderList (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ProviderList(struct soap*, ns1__ProviderList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ProviderList(struct soap*, ns1__ProviderList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ProviderList(struct soap*, const char *, int, ns1__ProviderList *const*, const char *);
SOAP_FMAC3 ns1__ProviderList ** SOAP_FMAC4 soap_get_PointerTons1__ProviderList(struct soap*, ns1__ProviderList **, const char*, const char*);
SOAP_FMAC3 ns1__ProviderList ** SOAP_FMAC4 soap_in_PointerTons1__ProviderList(struct soap*, const char*, ns1__ProviderList **, const char*);

#ifndef SOAP_TYPE_PointerTons1__AssetList
#define SOAP_TYPE_PointerTons1__AssetList (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__AssetList(struct soap*, ns1__AssetList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__AssetList(struct soap*, ns1__AssetList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__AssetList(struct soap*, const char *, int, ns1__AssetList *const*, const char *);
SOAP_FMAC3 ns1__AssetList ** SOAP_FMAC4 soap_get_PointerTons1__AssetList(struct soap*, ns1__AssetList **, const char*, const char*);
SOAP_FMAC3 ns1__AssetList ** SOAP_FMAC4 soap_in_PointerTons1__AssetList(struct soap*, const char*, ns1__AssetList **, const char*);

#ifndef SOAP_TYPE_PointerTons1__Asset
#define SOAP_TYPE_PointerTons1__Asset (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Asset(struct soap*, ns1__Asset *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Asset(struct soap*, ns1__Asset *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Asset(struct soap*, const char *, int, ns1__Asset *const*, const char *);
SOAP_FMAC3 ns1__Asset ** SOAP_FMAC4 soap_get_PointerTons1__Asset(struct soap*, ns1__Asset **, const char*, const char*);
SOAP_FMAC3 ns1__Asset ** SOAP_FMAC4 soap_in_PointerTons1__Asset(struct soap*, const char*, ns1__Asset **, const char*);

#ifndef SOAP_TYPE_PointerTons1__Cluster
#define SOAP_TYPE_PointerTons1__Cluster (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Cluster(struct soap*, ns1__Cluster *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Cluster(struct soap*, ns1__Cluster *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Cluster(struct soap*, const char *, int, ns1__Cluster *const*, const char *);
SOAP_FMAC3 ns1__Cluster ** SOAP_FMAC4 soap_get_PointerTons1__Cluster(struct soap*, ns1__Cluster **, const char*, const char*);
SOAP_FMAC3 ns1__Cluster ** SOAP_FMAC4 soap_in_PointerTons1__Cluster(struct soap*, const char*, ns1__Cluster **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__Cluster
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__Cluster (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, std::vector<ns1__Cluster * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, const std::vector<ns1__Cluster * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, const char*, int, const std::vector<ns1__Cluster * >*, const char*);
SOAP_FMAC3 std::vector<ns1__Cluster * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, const char*, std::vector<ns1__Cluster * >*, const char*);
SOAP_FMAC5 std::vector<ns1__Cluster * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, std::vector<ns1__Cluster * >*);
SOAP_FMAC3 std::vector<ns1__Cluster * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__Cluster(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfstd__string
#define SOAP_TYPE_std__vectorTemplateOfstd__string (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfstd__string(struct soap*, std::vector<std::string >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfstd__string(struct soap*, const std::vector<std::string >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfstd__string(struct soap*, const char*, int, const std::vector<std::string >*, const char*);
SOAP_FMAC3 std::vector<std::string >* SOAP_FMAC4 soap_in_std__vectorTemplateOfstd__string(struct soap*, const char*, std::vector<std::string >*, const char*);
SOAP_FMAC5 std::vector<std::string > * SOAP_FMAC6 soap_new_std__vectorTemplateOfstd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfstd__string(struct soap*, std::vector<std::string >*);
SOAP_FMAC3 std::vector<std::string > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfstd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfstd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of LAMFacadeForCMEH.h */
