use vars qw(@AssetGear @EventCollector @TAO_APIS @VOD_APIS %AssetGear %EventCollector @All_Services);
%AssetGear = (
               'name'             => 'AssetGear',
               'dependencies'     => ["AssetGear.exe","AssetGear.pdb","PMclient.dll","PMclient.pdb","IDSAPI.DLL","mcaapidll.dll"],
               'Registry'         => \@AssetGear,
                 );
%EventCollector = (
               'name'             => 'EventCollector',
               'dependencies'     => ["EventCollector.exe","IsaMessages.dll","IsaAlarm.ini","boost_regex_vc6_mdi.dll","jmsc.dll",""],
               'Registry'         => \@EventCollector,
                 );
@TAO_APIS = (
             "TAO_CosNotification.dll",
             "TAO_Strategies.dll",
             "TAO_PortableServer.dll",
             "TAO_CosNaming.dll",
             "TAO_ETCL.dll",
             "TAO_IORTable.dll",
             "TAO_Messaging.dll",
             "TAO_Svc_Utils.dll",
             "TAO_CosEvent.dll",
             "TAO_DynamicAny.dll",
             "TAO.dll",
             "ACE.dll",
             "ACEXML.dll",
             "ACEXML_Parser.dll",
            );
@VOD_APIS = (
             "REPORTER.DLL",
             "ManPkgU.dll",
             "cfgpkgU.dll",
             "CLOG.DLL",
             "queue.dll",
             "ScThreadPool.dll",
             "ShellMsgs.dll",
             "ItvMessages.dll",
             "libexpat.dll",
             "MCastSvc.dll",
             "MtTcpComm.dll",
             "IDSAPI.DLL",
             "MCAApiDll.dll",
             "atomic_queues.dll",
            );
@EventCollector = (
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector","Config File Name","ConfigFileName","%EXEDIR%\\IsaAlarm.ini","S",],
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector","Specify path of the crashdump files save","CrashDumpPath","%CRASHDIR%","S"],
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector","The size of Log File","LogFileSize","0xA00000","D"],
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector","ZQ log file output level, {0-7}, 7 is the debug level","LogLevel","7","D"],
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector","Keep alive Interverls for appshell","KeepAliveIntervals","0x002ee0","D"],
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector","Shut down wait time, in ms","ShutdownWaitTime","0x000064","D"],
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector","The name of Log File","LogFileName","%LOGDIR%\\EventCollector.log","S"],
                   ["SYSTEM\\CurrentControlSet\\Services\\EventCollector","Product Name","ProductName","ITV","S"],
                   ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\EventCollector","Event Message File of EventCollector","EventMessageFile","%EXEDIR%\\ItvMessages.dll","E"],
                   ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\EventCollector","The type of support of EventCollector","Typessupported","7","D"],
                   ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\EventCollector","Management Port Number of EventCollector","MgmtPortNumber","6900","D"],
                   ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\EventCollector_shell","Management Port Number of EventCollector_shell","MgmtPortNumber","6901","D"],
                   ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\EventCollector_shell","SrvShell image file pathname","ImagePath","%EXEDIR%\\EventCollector.exe","E",],
                   ["SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment","class path","classpath","%JBOSSCLIENT%;%JBOSSCLIENT%\\jbossall-client.jar","E"],
                  );
@AssetGear = (
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","The log file name of assetgear","LogFile","%LOGDIR%\\AssetGear.log","S",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Specify path of the crashdump files save","CrashDumpPath","%CRASHDIR%","S",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","The size of Log File","LogFileSize","0xA00000","D",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","ZQ log file output level","LogLevel","900","D",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Define if create asset fail when query metadata failed","UpdateMdFailCreateAssetFail","1","D",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Specifies the url of AssetGear service, ip 0.0.0.0 means bound to any available address. ","AssetGearUrl","http://0.0.0.0:1200/services/AssetGearService","S",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Soap Tread Pool","SoapThreadPool","10","D",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Specifies the url of PMService ","MetadataGatewayUrl","http://MetadataGateway:8000/services/PMService","S",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Specifies the server name and port number which AssetGear service is bound to.(CORBA)","ORBEndpoint","iiop://xx.xx.xx.xx:32120","S",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Specify the EndPoint of isaContent service","ContentStoreEndPoint","SeaChangeContentStore:33333","S"],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Specify the itv file import path configured for IAM service of this site","ItvImportPath","You must set manual","S",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear","Tao Thread Pool","TaoThreadPool","10","D",],
              ["SYSTEM\\CurrentControlSet\\Services\\AssetGear","Product Name","ProductName","ITV","S",],
              ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\AssetGear","Event Message File of AssetGear","EventMessageFile","%EXEDIR%\\ItvMessages.dll","E",],
              ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\AssetGear","The type of Supported of AssetGear","Typessupported","7","D",],
              ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\AssetGear_shell","Event Message File of AssetGear_shell","EventMessageFile","%EXEDIR%\\ShellMsgs.dll","E",],
              ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\AssetGear_shell","The type of Supported of AssetGear_shell","Typessupported","7","D",],
              ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\AssetGear","Management Port Number of AssetGear","MgmtPortNumber","6861","D",],
              ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\AssetGear_shell","Management Port Number of AssetGear_shell","MgmtPortNumber","6862","D",],
              ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\AssetGear_shell","Image Path","ImagePath","%EXEDIR%\\AssetGear.exe","E",],
             );
@All_Services = (
                 \%AssetGear,
                 \%EventCollector,
                );