
#ifndef MESSAGEHEADER_H
#define MESSAGEHEADER_H

#define MESSAGEFLAG		_T("Message")
#define MESSAGEHEADER		_T("MessageHeader")
#define MESSAGECODE			_T("MessageCode")
#define MESSAGETIME			_T("MessageTime")
#define MESSAGERETURN		_T("BeReturn")
#define MESSAGEBODY				_T("MessageBody")
#define MESSAGECONFIG				_T("DODDeviceController")

#define MESSAGEDODPORT				_T("DODPort") 
#define MESSAGEPMTPID				_T("PMTPID") 
#define MESSAGETOTALBITRATE			_T("TotalBitRate") 
#define MESSAGETMPPATH				_T("TmpPath") 
#define MESSAGESOURCEDIR			_T("SourceDirectory") 
#define MESSAGEIPPORT					_T("IPPort")
#define MESSAGEDODCHANNEL				_T("DODChannel") 
#define MESSAGECHANNELTYPE				_T("ChannelType") 
#define MESSAGESTREAMID					_T("StreamID") 
#define MESSAGEREPEATTIME				_T("RepeatTime") 
#define MESSAGECHANNELTAG				_T("Tag") 
#define MESSAGEBITRATE					_T("BitRate") 
#define MESSAGESTREAMTYPE				_T("StreamType") 

#define MESSAGEDETECT					_T("BeDetect") 
#define MESSAGEDETECTINTERVAL			_T("BeDetectInterval") 
#define MESSAGEENCRYPTED				_T("BeEncrypted") 
#define MESSAGEDETECTPATH				_T("DetectPath") 

#define MESSAGECARDID			_T("CardID") 
#define MESSAGEBAND				_T("BrandWith")

#define MESSAGEPORTID			_T("PortID")
#define MESSAGEPMTPID			_T("PMTPID")
#define MESSAGEBITRATE			_T("BitRate")
#define MESSAGETMPFILEPATH		_T("TmpFilePath")

#define MESSAGECHANNELID		_T("ChannelID")
#define MESSAGEINTERVAL			_T("Interval")
#define MESSAGEENABLED			_T("Enabled")
#define MESSAGEFORCED			_T("Forced")
#define MESSAGECHVERSION		_T("ChannelVersion")
#define MESSAGEOBJKEYLEN		_T("ObjKeyLength")
#define MESSAGECHIDXDESLEN		_T("ChIdxDesLen")
#define MESSAGEFILENAME			_T("FileName")
#define MESSAGEFREQUENCY		_T("Frequency")
#define MESSAGECATALOGNAME		_T("Catalog")

// Virtual Port Controller
#define MESSAGECODE_CONFIG				1101
#define MESSAGECODE_INITDEVICE			1102
#define MESSAGECODE_GETBANDWIDTH		1103
#define MESSAGECODE_GETCARDIPPORT		1104
#define MESSAGECODE_GETUSEDIPPORT		1105

// Port
#define MESSAGECODE_OPEN				1201
#define MESSAGECODE_CLOSE				1202
#define MESSAGECODE_PAUSE				1203
#define MESSAGECODE_RUN					1204
#define MESSAGECODE_STOP				1205
#define MESSAGECODE_GETPORTSTATE		1206
#define MESSAGECODE_SETPORTPMTPID		1207
#define MESSAGECODE_GETPORTPMTPID		1208
#define MESSAGECODE_SETTOTALBITRATE		1209
#define MESSAGECODE_GETTMPFILEPATH		1210
#define MESSAGECODE_SETTMPFILEPATH		1211
#define MESSAGECODE_GETPORT				1212

// Channel
#define MESSAGECODE_GETCHANNEL				1301
#define MESSAGECODE_ENABLECHANNELDETECTED	1302
#define MESSAGECODE_SETDETECTINTERVAL		1303
#define MESSAGECODE_FORCEREDETECTED			1304
#define MESSAGECODE_ADDCHANNELVERSION		1305
#define MESSAGECODE_RESETCHANNELVERSION		1306
#define MESSAGECODE_SETCHANNELVERSION		1307
#define MESSAGECODE_SETOBJKEYLENGTH			1308
#define MESSAGECODE_SETIDXDESLEN			1309
#define MESSAGECODE_ENABLECHANNEL			1310
#define MESSAGECODE_SETCHANNELBITRATE		1311

// Sub Channel
#define MESSAGECODE_GETSUBCHANNEL			1312
#define MESSAGECODE_SETSUBCHANNELFREQ		1313
#define MESSAGECODE_GETSUBCHANNELFREQ		1315

// append
#define MESSAGECODE_SETCATALOGNAME			1316
#define MESSAGECODE_GETCATALOGNAME			1317
//#define MESSAGECODE_UPDATECATALOGNAME		1318	
#define MESSAGECODE_DISABLECHANNELDETECTED	1319
#define MESSAGECODE_GETTOTALBITRATE			1320
#define MESSAGECODE_GETCHANNELDETECTED		1321
#define MESSAGECODE_GETDETECTINTERVAL		1322
#define MESSAGECODE_GETCHANNELVERSION		1323
#define MESSAGECODE_GETOBJKEYLENGTH			1324
#define MESSAGECODE_GETCHANNELIDXDESLEN		1325

#endif