${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2cpp  ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE  -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --dict "TianShanIce::Transport::ServiceGroupDict,long,TianShanIce::Transport::ServiceGroup" ServiceGroupDict ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --dict "TianShanIce::Transport::StorageDict,string,TianShanIce::Transport::Storage" StorageDict ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --dict "TianShanIce::Transport::StreamerDict,string,TianShanIce::Transport::Streamer" StreamerDict ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --index "TianShanIce::Transport::StorageToStorageLink,TianShanIce::Transport::StorageLink,storageId" StorageToStorageLink ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --index "TianShanIce::Transport::StreamerToStorageLink,TianShanIce::Transport::StorageLink,streamerId" StreamerToStorageLink ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --index "TianShanIce::Transport::StreamerToStreamLink,TianShanIce::Transport::StreamLink,streamerId" StreamerToStreamLink ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --index "TianShanIce::Transport::ServiceGroupToStreamLink,TianShanIce::Transport::StreamLink,servicegroupId" ServiceGroupToStreamLink ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --index "TianShanIce::Transport::StorageLinkToTicket,TianShanIce::Transport::PathTicket,storageLinkIden" StorageLinkToTicket ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I .  -I ${ZQProjsPath}/TianShan/AccreditedPath  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --index "TianShanIce::Transport::StreamLinkToTicket,TianShanIce::Transport::PathTicket,streamLinkIden" StreamLinkToTicket ${ZQProjsPath}/TianShan/AccreditedPath/TsPathAdmin.ICE --output-dir ${ZQProjsPath}/TianShan/AccreditedPath
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2cpp  ${ZQProjsPath}/TianShan/Weiwoo/WeiwooAdmin.ICE  -I .  -I ${ZQProjsPath}/TianShan/Weiwoo  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice   --output-dir ${ZQProjsPath}/TianShan/Weiwoo

