[ ] //******************************************************************************
[ ] //  NAME:           AQUARIUSFRAME.INC
[ ] //
[ ] //  DESCRIPTION:    Window Declarations used by Aquarius Tests.
[ ] //
[ ] //  HISTORY:
[ ] //
[ ] //  Date            Developer         Description
[ ] //  ********		***********		  ******************************************
[ ] //  01/31/03        C. Callahan       Created - defines the command window for
[ ] //                                    Aquarius Session Pl
[ ] //
[ ] //******************************************************************************
[ ] //111111102222222220333333333044444444405555555550666666666077777777708888888880
[ ] //******************************************************************************
[-] window DialogBox AquariusSessionPl
	[ ] tag "Aquarius Session Pl *"
[ ] 
