TOPDIR := ../../..

include $(TOPDIR)/build/defines.mk

SOLIB := CPCMan_web

OBJS := BasePage.os CPCMan_web.os CpcMethodController.os CpcServiceController.os stroprt.os

include $(TOPDIR)/build/common.mk
