use vars qw(@NSSync @struct @Filelist);
my @struct=(
         ["key","description","name","default","type","display or not, 1 enable, 0 disable"]
        );
@Filelist = (
              'NSSync.exe',
              'cfgpkgU.dll',
              'CLog.dll',
              'ctail.exe',
              'instserv.exe',
              'ItvMessages.dll',
              'ManPkgU.dll',
              'MCastSvc.dll',
              'MFC71u.dll',
              'msvcp71.dll',
              'msvcr71.dll',
              'MtTcpComm.dll',
              'queue.dll',
              'Reporter.dll',
              'ReporterMsgs.dll',
              'ScThreadPool.dll',
              'ShellMsgs.dll',
              'srvshell.exe',
              );

@NSSync = (
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Instance","Instance","1","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","KeepAliveIntervals","KeepAliveIntervals","2000","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogBufferSize","LogBufferSize","4096","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogFileName","LogFileName","%LOGDIR%\\NSSync.log","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogFileSize","LogFileSize","40960000","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogFileTimeOut","LogFileTimeOut","2000","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogLevel","LogLevel","7","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","ShutdownWaitTime","ShutdownWaitTime","10000","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","SuperviseInterval","SuperviseInterval","60","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","DB connection/operation timeout in seconds","IZQDBTimeout","600","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","DB re-connection interval in seconds","IZQDBConnRetryInterval","10","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","DSN name for NSSync to connect local database","IZQDBDSN","LAM","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Username for NSSync to access local database","IZQDBUserName","am","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Password for NSSync to access local database","IZQDBPassword","am","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Local database name for NSSync to access","IZQDBName","am","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Local database type","IZQDBType","SQL Server","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","The time interval in millisecond for NSSync to retrieve data from local database","TeaTime","500","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Region ID for current NSSync instance","RegionID","TWT","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","A ceiling number, once the workqueue records reach the celling, NSSync will do rebuild instead of process one by one","MaxWQOptRebuild","100","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename_shell","ImagePath","ImagePath","%EXEDIR%\\NSSync.exe","S","1"],
                ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\$servicename","Management Port Number for NSSync","MgmtPortNumber","0x00001B18","D","1"],
                ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\$servicename_shell","Management Port Number for NSSync_shell","MgmtPortNumber","0x00001B19","D","1"],
                ["SYSTEM\\CurrentControlSet\\Services\\$servicename","Product Name","ProductName","ITV","S","1"],
                ["SYSTEM\\CurrentControlSet\\Services\\$servicename","ImagePath of SrvShell","ImagePath","%EXEDIR%\\SrvShell.exe","S","1"],
		["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename","The Event Message File of NSSync","EventMessageFile","%EXEDIR%\\ItvMessages.dll","S","1"],
		["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename","The type of Supported of NSSync","Typessupported","7","D","1"],
                ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename_shell","The Event Message File Of NSSync_shell","EventMessageFile","%EXEDIR%\\ShellMsgs.dll","S","1"],
                ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename_shell","The type of Supported Of NSSync_shell","Typessupported","7","D","1"],
                );