
#ifndef MESSAGEHEADER_H
#define MESSAGEHEADER_H

#define JMSMESSAGE_DESTIONATIONFILENAME		6

//For DODMessage

#define DODMESSAGEFLAG			_T("DODMessage")
#define DODMESSAGEHEADER		_T("DODMessageHeader")
#define DODMESSAGECODE			_T("MessageCode")
#define DODMESSAGETIME			_T("Time")
#define DODMESSAGERETURN		_T("BeReturn")
#define DODMESSAGEBODY			_T("DODMessageBody")

// For message content
#define DODMESSAGECONTENT		_T("Message")
#define MESSAGEDATATYPE			_T("DataType")
#define MESSAGEDODSTARTUP		_T("DODStartup")
#define MESSAGEGROUPID			_T("GroupID")
#define MESSAGEVERSIONNUM		_T("Version")
#define MESSAGEMESSAGEID		_T("MessageID")
#define MESSAGEOPERATION		_T("operation")
#define MESSAGECONFREQUEST		_T("ConfRequest")
#define MESSAGECONFREQUESTKEY	_T("Key")
#define MESSAGEGROUPIDAPPNAME	_T("AppName")
#define MESSAGETYPE				_T("Type")
#define MESSAGEFORMAT			_T("Format")
#define CONTENTMESSAGEDOD		_T("DOD")
#define CONTENTFILEOPERATION	_T("FileOperation")
#define CONTENTRESPONSECODE		_T("ResponseCode")
#define CONTENTCONFRESPONSE		_T("ConfResponse")
#define CONTENTUPDATEMODE		_T("UpdateMode")
#define CONTENTROOT				_T("Root")
#define CONTENTFILE				_T("File")
#define CONTENTPATH				_T("Path")

//For ConfigMessage
#define DODMESSAGECONFIG		_T("DODDeviceController")
#define MESSAGEDODPORT				_T("DODPort") 
#define MESSAGEPMTPID				_T("PMTPID") 
#define MESSAGETOTALBITRATE			_T("TotalBitRate") 
#define MESSAGETMPPATH				_T("TmpPath") 
#define MESSAGESOURCEDIR			_T("SourceDirectory") 
#define MESSAGEDODCHANNEL				_T("DODChannel") 
#define MESSAGECHANNELTYPE				_T("ChannelType") 
#define MESSAGESTREAMID					_T("StreamID") 
#define MESSAGEREPEATTIME				_T("RepeatTime") 
#define MESSAGECHANNELTAG				_T("Tag") 
#define MESSAGEBITRATE					_T("BitRate") 
#define MESSAGEDETECT					_T("BeDetect") 
#define MESSAGEDETECTINTERVAL			_T("BeDetectInterval") 
#define MESSAGEENCRYPTED				_T("BeEncrypted") 

#define MESSAGECARDID			_T("CardID") 
#define MESSAGEBAND				_T("BrandWith")

#define MESSAGEPORTID			_T("PortID")
#define MESSAGEPMTPID			_T("PMTPID")
#define MESSAGEBITRATE			_T("BitRate")
#define MESSAGETMPFILEPATH		_T("TmpFilePath")

#define MESSAGECHANNELID		_T("ChannelID")
#define MESSAGEINTERVAL			_T("Interval")
#define MESSAGEENABLED			_T("Enabled")
#define MESSAGEFORCED			_T("Forced")
#define MESSAGECHVERSION		_T("ChannelVersion")
#define MESSAGEOBJKEYLEN		_T("ObjKeyLength")
#define MESSAGECHIDXDESLEN		_T("ChIdxDesLen")
#define MESSAGEFILENAME			_T("FileName")
#define MESSAGEFREQUENCY		_T("Frequency")
#define MESSAGECATALOGNAME		_T("Catalog")

// Virtual Port Controller
#define MESSAGECODE_CONFIG				1001
#define MESSAGECODE_INITDEVICE			1002
#define MESSAGECODE_GETBANDWIDTH		1003
#define MESSAGECODE_GETCARDIPPORT		1004
#define MESSAGECODE_GETUSEDIPPORT		1005

// Port
#define MESSAGECODE_OPEN				2001
#define MESSAGECODE_CLOSE				2002
#define MESSAGECODE_PAUSE				2003
#define MESSAGECODE_RUN					2004
#define MESSAGECODE_STOP				2005
#define MESSAGECODE_GETPORTSTATE		2006
#define MESSAGECODE_SETPORTPMTPID		2007
#define MESSAGECODE_GETPORTPMTPID		2008
#define MESSAGECODE_SETTOTALBITRATE		2009
#define MESSAGECODE_GETTMPFILEPATH		2010
#define MESSAGECODE_SETTMPFILEPATH		2011
#define MESSAGECODE_GETPORT				2012

// Channel
#define MESSAGECODE_GETCHANNEL					3001
#define MESSAGECODE_ENABLECHANNELDETECTED		3002
#define MESSAGECODE_SETDETECTINTERVAL			3003
#define MESSAGECODE_FORCEREDETECTED				3004
#define MESSAGECODE_ADDCHANNELVERSION			3005
#define MESSAGECODE_RESETCHANNELVERSION			3006
#define MESSAGECODE_SETCHANNELVERSION			3007
#define MESSAGECODE_SETOBJKEYLENGTH				3008
#define MESSAGECODE_SETIDXDESLEN			3009
#define MESSAGECODE_ENABLECHANNEL			3010
#define MESSAGECODE_SETCHANNELBITRATE		3011

// Sub Channel
#define MESSAGECODE_GETSUBCHANNEL			3012
#define MESSAGECODE_SETSUBCHANNELFREQ		3013
#define MESSAGECODE_GETSUBCHANNELFREQ		3015

// append
#define MESSAGECODE_SETCATALOGNAME			3016
#define MESSAGECODE_GETCATALOGNAME			3017
//#define MESSAGECODE_UPDATECATALOGNAME		3018	
#define MESSAGECODE_DISABLECHANNELDETECTED	3019
#define MESSAGECODE_GETTOTALBITRATE			3020
#define MESSAGECODE_GETCHANNELDETECTED		3021
#define MESSAGECODE_GETDETECTINTERVAL		3022
#define MESSAGECODE_GETCHANNELVERSION		3023
#define MESSAGECODE_GETOBJKEYLENGTH			3024
#define MESSAGECODE_GETCHANNELIDXDESLEN		3025

#define NO_USE_JMS					2	//(local file)
#define DETECTINTERVAL				5000
#define DATAEXCHANGETYPE_MESSAGE_FORMAT		1

// JMS Message code
#define JMSMESSAGE_CONFIGURATION		1515


#define DATATYPE_NAVIGATION			11
#define DATATYPE_PORTAL				14
#define DATATYPE_POSTER				15

#define DATATYPE_ILP_NAVIGATION		1021
#define DATATYPE_ILP_PORTAL			1023
#define DATATYPE_ILP_POSTER			1022

/*
// channel datatype

#define DATATYPE_CHANNELLINEUP		12
#define DATATYPE_PO					13
#define DATATYPE_STBCONFIG			16
#define DATATYPE_MYTICKET			17

#define DATATYPE_SYSTEMMESSAGE		21
#define DATATYPE_OSS				22
#define DATATYPE_PROVISION			23
#define DATATYPE_TICPACCESSCODE		24
#define DATATYPE_STBUPGRADE			25
#define DATATYPE_HOTEL				26
#define DATATYPE_MYTICKETMSG		27


11     Navigation
12     Channel Lineup
13     PO
14    Portal
15    Poster
Message
21     System message
22     Entitlement
23     Provision
24     TICP access code



// JMS Message code
#define JMSMESSAGE_CONFIGURATION		1515

#define JMSMESSAGE_NAVIGATION			1411
#define JMSMESSAGE_CHANNELLINEUP		1513
#define JMSMESSAGE_PO					1311
#define JMSMESSAGE_PORTAL				1514
#define JMSMESSAGE_POSTER				0
#define JMSMESSAGE_STBCONFIG			1523

#define JMSMESSAGE_SYSTEMMESSAGE		0
#define JMSMESSAGE_HOTEL				2041
#define JMSMESSAGE_OSS					2042
#define JMSMESSAGE_PROVISION			0
#define JMSMESSAGE_TICPACCESSCODE		1911
#define JMSMESSAGE_STBUPGRADE			1516

#define JMSMESSAGE_TOMYTICKETMSG		1331
*/

#endif