[ ] //*****************************************************************************
[ ] //  NAME:					  ZODIACMSGS.INC
[ ] //
[ ] //  DESCRIPTION:		Common messages file for all Zodiac components.
[ ] //
[ ] //  HISTORY:
[ ] //
[ ] //  Date						Developer					Description
[ ] //  ********				***********				*****************************************
[ ] //  11/21/02        M. Albanese       Initial design and development
[ ] //  11/12/02				M. Albanese				Added add'l err and generic messages.
[ ] //
[ ] //*****************************************************************************
[ ] 
[ ] //*****************************************************************************
[ ] // ERROR MESSAGES
[ ] //*****************************************************************************
[ ] 
[ ] const string cerrIniNotFound 				= "Specified ini file not found."
[ ] const string cerrBadOpType 					= "Request was neither a Read or Write."
[ ] const string cerrBadSectionOrValue 	= "Bad section name or entry is empty."
[ ] const string cerrAutoGenIni 				=	"4Test generated an empty ini."
[ ] const string cerrLogNotCreated			=	"Pass/Fail log not created."
[ ] const string cerrFileNotFound				=	"Specified path/filename not found."
[ ] 
[ ] //*****************************************************************************
[ ] // GENERIC MESSAGES
[ ] //***************************************************************************** 
[ ] 
[ ] const string cmsgExpReadOrWrite			=	"Read or Write request, "
[ ] const string cmsgExpValidRetVal 		= "A valid ini return value, "
[ ] const string cmsgLogCreated					=	"Pass/Fail Log created, "
[ ] const string cmsgValidFile					=	"Valid path and/or filename, "
[ ] 
[ ] //*****************************************************************************
[ ] // END: ZODIACMSGS.INC
[ ] //*****************************************************************************
