[ ] //*****************************************************************************
[ ] //  NAME:					  SCORPIODEFS.INC
[ ] //
[ ] //  DESCRIPTION:		Constant definitions specific to the Scorpio component.
[ ] //                  
[ ] //
[ ] //  HISTORY:
[ ] //
[ ] //  Date						Developer					Description
[ ] //  ********				***********				*****************************************
[ ] //  01/03/03        M. Albanese       Initial design and development
[ ] //
[ ] //*****************************************************************************
[ ] 
[ ] //*****************************************************************************
[ ] // FILENAMES (fil)
[ ] //*****************************************************************************
[ ] 
[ ] //*****************************************************************************
[ ] // INI/ITV FILE SECTIONS (sec)
[ ] //*****************************************************************************
[ ] 
[ ] const secAssetData						=	"AssetData"
[ ] const	secContent							=	"Content"
[ ] const	secImport								=	"Import"
[ ] const	secITVServers						=	"ITVServers"
[ ] const secMD_20008001					=	"metadata_200080001"
[ ] const secMD_30008001					=	"metadata_300080001"
[ ] const secUid									=	"uid"
[ ] // const secVideoServers					=	"VideoServers"
[ ] 
[ ] //*****************************************************************************
[ ] // INI/ITV FILE ENTRIES (ent)
[ ] //*****************************************************************************
[ ] 
[ ] const	entActivateTime					=	"ActivateTime"
[ ] const entActiveDate						=	"ActiveDate"
[ ] const	entAmName								=	"AmName"
[ ] const entAeActivate						=	"AeActivate"
[ ] const entAeDeactivate					=	"AeDeactivate"
[ ] const entAeDelete							=	"AeDelete"
[ ] const entAeID									=	"AeID"
[ ] const entAeName1							=	"AeName1"
[ ] const entAeName1DT						=	"AeName1DT"
[ ] const entAeRelease						=	"AeRelease"
[ ] const entAeUpload							=	"AeUpload"
[ ] const entAssetActivate				=	"AssetActivate"
[ ] const entAssetDeactivate			=	"AssetDeactivate"
[ ] const entAssetID							=	"AssetID"
[ ] const entAssetName1						=	"AssetName1"
[ ] const entAssetName1DT					=	"AssetName1DT"
[ ] const entCMName								=	"CmName"
[ ] const	entContentPath					=	"ContentPath"
[ ] const	entContentFileName1			=	"ContentFileName1"
[ ] const entDeactivateTime				=	"DeactivateTime"
[ ] const entDeactiveDate					=	"DeactiveDate"
[ ] const entDeleteDate						=	"DeleteDate"
[ ] const entExpRepCount					=	"ExpectedReplicaCount"
[ ] const entFileName							=	"FileName"
[ ] const entFilePath							=	"FilePath"
[ ] const entFolder								=	"Folder"
[ ] const entImportedDir					=	"ImportedDir"
[ ] const entImportPath						=	"ImportFromPath"
[ ] const entITVMasterDataFile		=	"ITVMasterDataFile"
[ ] const entITVMasterDataPath		=	"ITVMasterDataPath"
[ ] const entITVWorkingDataFile		=	"ITVWorkingDataFile"
[ ] const entITVWorkingDataPath		=	"ITVWorkingDataPath"
[ ] const entLastWorkingDataFile	=	"LastWorkingDataFile"
[ ] const entLastWorkingRptFile		=	"LastWorkingReportFile"
[ ] const entReleaseDate					=	"ReleaseDate"
[ ] const entUploadClusterName		=	"UploadClusterName"
[ ] const entUploasClusterIP			=	"UploadClusterIP"
[ ] const entUploadDate						=	"UploadDate"
[ ] const ent200080001						=	"200080001"
[ ] const ent300080001						=	"300080001"
[ ] 
[ ] //*****************************************************************************
[ ] // MISCELLANEOUS STRINGS
[ ] //*****************************************************************************
[ ] 
[ ] const csAe										=	"; Ae:"
[ ] const csAsset									=	"; Asset: "
[ ] const csMetadata							=	"; Metadata:"
[ ] const csEmptyString						=	""
[ ] 
[ ] //*****************************************************************************
[ ] // END: SCORPIODEFS.INC
[ ] //*****************************************************************************
