use vars qw(@DBSync @struct @Filelist);
my @struct=(
         ["key","description","name","default","type","display or not, 1 enable, 0 disable"]
        );

@Filelist = (
              'DBSync.exe',
              'cfgpkgU.dll',
              'CLog.dll',
              'ctail.exe',
              'idsapi.dll',
              'Ipsapi.dll',
              'instserv.exe',
              'ItvMessages.dll',
              'ManPkgU.dll',
              'MCastSvc.dll',
              'mfc42u.dll',
              'msvcr71.dll',
              'mfc71.dll',
              'msvcp71.dll',
              'mfc71u.dll',
              'msvcp60.dll',
              'MtTcpComm.dll',
              'queue.dll',
              'Reporter.dll',
              'ScThreadPool.dll',
              'ShellMsgs.dll',
              'srvshell.exe',
              'IDSSyncEventPlugin.dll',
              'IDSSyncEventPlugin.ini',
              'jmsc.dll',
              'ManualSyncPlugin.dll',
              );

@DBSync = (
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Instance","Instance","1","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","KeepAliveIntervals","KeepAliveIntervals","2000","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogBufferSize","LogBufferSize","65536","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogFileName for DBSync","LogFileName","%LOGDIR%\\DBSync.log","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogFileSize for DBSync","LogFileSize","20000000","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogFileTimeOut for DBSync","LogFileTimeOut","2000","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","LogLevel for DBSync","LogLevel","7","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","ShutdownWaitTime","ShutdownWaitTime","8000","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Support Ref count Rating Ctrl","SupportRefcountRatingCtrl","0","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","The IP of ITV IDS running on to take API call","ITVServerAddress","<IpAddress>","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Username to represent the IDSAPI client","ITVUserName","DBSync","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","DSN name for DBSync to connect local database","IZQDBDSN","multiverse","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Username for DBSync to access local database","IZQDBUserName","multiverse","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Password for DBSync to access local database","IZQDBPassword","multiverse","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Local database type","IZQDBType","SQL Server","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","The play interval time","IZQPlayInterval","0","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","The interval time in minutes to check the connection between DBSync and ITV IDS","ITVCheckInterval","60","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","The synchronization folder path in ITV AM","SyncDirectory","\\","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Time window threshold for some asset metadata","TimeWindowThreshold","600","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Flag to enable or disable the sync speed optimization","SupportUpdateStamp","1","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Flag to enable or disable generate xml file for IngestManager component","SupportIngestManager","1","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Whether the synced folder itself linked to LAM","SyncedFolderAsNavNode","0","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Synchronize all at the beginning of the service start,1 for enable,0 for disable","SyncAllAtBegin","1","D","0"],                
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","Ignore Replace Operation FolderCallback, 1 for ignore,0 for does not ignore","IgnoreReplaceOpFolderCallback","0","D","0"],                
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","retry count for the sql failure caused by deadlock ","SQLDeadlockRetryCount","3","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename_shell","ImagePath","ImagePath","%EXEDIR%\\DBSync.exe","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename_shell","LogfilePath","LogfilePath","%LOGDIR%\\DBSync_shell.log","S","0"],                
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","The DBSync plugin dll file name to support sending sync event to 3rd application by JMS","IDSSyncEventPluginPath","%EXEDIR%\\IDSSyncEventPlugin.dll","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","ContextName","NamingContext","org.jnp.interfaces.NamingContextFactory","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","JBoss server IP Address connect for IDSSyncEventPlugin","JmsServerIP","<IPAddress>","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","JBoss server IP Port connect for IDSSyncEventPlugin","JmsServerPort","1234","D","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","DBSync server IP Address","DBSyncIP","<IPAddress>","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","name of destination","DestinationName","topic/testTopic","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","name of connection factory","ConnectionFactory","ConnectionFactory","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","IDSSyncEventPlugin config file","IniFilePath","%EXEDIR%\\IDSSyncEventPlugin.ini","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","IDSSyncEventPlugin log file name","LogPath","%LOGDIR%\\IDSSyncEventPlugin.log","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","log file size for IDSSyncEventPlugin","LogFileSize","10000000","D","0"],                
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","log buffer size for IDSSyncEventPlugin","LogBufferSize","65536","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","LogFileSize for IDSSyncEventPlugin","LogWriteTimeOut","2","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","cycle count of send one message if it doesn't success","SendMsgCycleCount","3","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","interval of re-connect in millsecond","MillCountReConnect","5000","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","interval of send message in millsecond","MillIntervalSendMsg","100","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\IDSSyncEventPlugin","alive time of send message","KeepAliveTime","5000","D","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename","File path of DBSync plugin ManualSyncPlugin","ManualSyncPluginPath","%EXEDIR%\\ManualSyncPlugin.dll","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\ManualSyncPlugin","context name for ManualSyncPlugin","NamingContext","org.jnp.interfaces.NamingContextFactory","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\ManualSyncPlugin","name of send destination for ManualSyncPlugin","SendDesinationName","queue/queue_LAM","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\ManualSyncPlugin","name of receive destination for ManualSyncPlugin","RecvDesinationName","queue/queue_DBSYNC","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\ManualSyncPlugin","connection factory for ManualSyncPlugin","ConnectionFactory","ConnectionFactory","S","0"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\ManualSyncPlugin","Jboss server IP Address connected for ManualSyncPlugin","JmsServerIP","<IPAddress>","S","1"],
                ["SOFTWARE\\SeaChange\\ITV\\CurrentVersion\\Services\\$servicename\\ManualSyncPlugin","Jboss server port connected for ManualSyncPlugin","JmsServerPort","1234","D","1"],
                ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\$servicename","Management Port Number for DBSync","MgmtPortNumber","0x0000189F","D","0"],
                ["SOFTWARE\\SeaChange\\Management\\CurrentVersion\\Services\\$servicename_shell","Management Port Number for DBSync_shell","MgmtPortNumber","0x000018A0","D","0"],
                ["SYSTEM\\CurrentControlSet\\Services\\$servicename","Product Name","ProductName","ITV","S","0"],
                ["SYSTEM\\CurrentControlSet\\Services\\$servicename","ImagePath of SrvShell","ImagePath","%EXEDIR%\\SrvShell.exe","S","0"],
		["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename","The Event Message File of DBSync","EventMessageFile","%EXEDIR%\\ItvMessages.dll","S","0"],
		["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename","The type of Supported of DBSync","Typessupported","7","D","0"],
                ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename_shell","The Event Message File Of DBSync_shell","EventMessageFile","%EXEDIR%\\ShellMsgs.dll","S","0"],
                ["SYSTEM\\CurrentControlSet\\Services\\Eventlog\\Application\\$servicename_shell","The type of Supported Of DBSync_shell","Typessupported","7","D","0"],
                );                