
#ifndef _CPE_ERROR_CODE_HEADER_
#define _CPE_ERROR_CODE_HEADER_


const int ERRCODE_NULL_SESSION			= 100;
const int ERRCODE_UNSUPPORT_METHOD		= 101;
const int ERRCODE_PARAMS_MISSING		= 102;
const int ERRCODE_PUSHSOURCE_MISSING	= 103;
const int ERRCODE_BUFFERQUEUE_FULL		= 104;
const int ERRCODE_INVALID_SRCURL		= 105;
const int ERRCODE_SCHEDULE_EXPIRED		= 106;
const int ERRCODE_USER_CANCELED			= 107;
const int ERRCODE_AQUA_NOTINIT = 108;

const int ERRCODE_NTFS_CREATEFILE       = 200;
const int ERRCODE_NTFS_WRITEFILE		= 201;
const int ERRCODE_NTFS_READFILE			= 202;

const int ERRCODE_READ_SOURCE			= 260;

const int ERRCODE_VSTRM_API_ERROR       = 300;
const int ERRCODE_VSTRM_BANDWIDTH_EXCEEDED    = 301;
const int ERRCODE_VSTRM_DISK_FULL		= 302;
const int ERRCODE_VSTRM_NOT_READY		= 303;
const int ERRCODE_VSTRM_BUFFERQUEUE_FULL	= 304;

const int ERRCODE_PACING_ERROR			= 350;
const int ERRCODE_PACING_UNKNOWN_EXCEPTION	= 351;

const int ERRCODE_RTFLIB_ERROR			 = 400;
const int ERRCODE_RTFLIB_OPENSESSSION_FAIL = 401;
const int ERRCODE_RTFLIB_PROCESSBUFF_FAIL  = 402;
const int ERRCODE_RTFLIB_UNRECOVER_OVERFLOW = 403;
const int ERRCODE_RTFLIB_FATAL_ERROR		= 404;
const int ERRCODE_RTFLIB_OPENSESS_EXCEPTION = 405;

const int ERRCODE_TRICKGEN_CREATECONTEXT   = 501;
const int ERRCODE_TRICKGEN_PROCESSPIC_FAIL = 502;

const int ERRCODE_C2PULL_DOWNLOADFILE_FAIL = 601;

const int ERRCODE_C2PROPAGATION_DOWNLOADFILE_FAIL = 701;

const int ERRCODE_AQUAREC_FAILTORECORD = 801;
const int ERRCODE_AQUAREC_FAILTOGENERATEVIRSESS = 802;

const int ERRCODE_AQUA_CREATEFILE = 901;
const int ERRCODE_AQUA_WRITEFILE = 902;
const int ERRCODE_AQUA_READFILE = 903;

const int ERRCODE_AQUA_CSI_UNSUPPORT_PROTOCOL = 904;
const int ERRCODE_AQUA_CSI_ADDSESSION= 905;
const int ERRCODE_AQUA_CSI_UNKNOWN_CONTENTTYPE= 906;


#endif
