TOPDIR := ../../..

include $(TOPDIR)/build/defines.mk

LIB := NGODCS

OBJS := A3HttpReq.o cspNGOD.o HttpClient.o NGODCSEnv.o NGODStorePortal.o SimpleHttpd.o

INCDIR += ../../StreamService/NSS/

include $(TOPDIR)/build/common.mk
