/* soapH.h
   Generated by gSOAP 2.7.10 from soapMRT.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_ZQ2__Enum_1
#define SOAP_TYPE_ZQ2__Enum_1 (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__Enum_1(struct soap*, enum ZQ2__Enum_1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__Enum_1(struct soap*, const enum ZQ2__Enum_1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__Enum_1(struct soap*, const char*, int, const enum ZQ2__Enum_1 *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ZQ2__Enum_12s(struct soap*, enum ZQ2__Enum_1);
SOAP_FMAC3 enum ZQ2__Enum_1 * SOAP_FMAC4 soap_get_ZQ2__Enum_1(struct soap*, enum ZQ2__Enum_1 *, const char*, const char*);
SOAP_FMAC3 enum ZQ2__Enum_1 * SOAP_FMAC4 soap_in_ZQ2__Enum_1(struct soap*, const char*, enum ZQ2__Enum_1 *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ZQ2__Enum_1(struct soap*, const char*, enum ZQ2__Enum_1 *);

#ifndef SOAP_TYPE_ZQ2__setupInfo
#define SOAP_TYPE_ZQ2__setupInfo (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__setupInfo(struct soap*, const char*, int, const ZQ2__setupInfo *, const char*);
SOAP_FMAC3 ZQ2__setupInfo * SOAP_FMAC4 soap_get_ZQ2__setupInfo(struct soap*, ZQ2__setupInfo *, const char*, const char*);
SOAP_FMAC3 ZQ2__setupInfo * SOAP_FMAC4 soap_in_ZQ2__setupInfo(struct soap*, const char*, ZQ2__setupInfo *, const char*);
SOAP_FMAC5 ZQ2__setupInfo * SOAP_FMAC6 soap_new_ZQ2__setupInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__setupInfo(struct soap*, ZQ2__setupInfo*);
SOAP_FMAC3 ZQ2__setupInfo * SOAP_FMAC4 soap_instantiate_ZQ2__setupInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__setupInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__map
#define SOAP_TYPE_ZQ2__map (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__map(struct soap*, const char*, int, const ZQ2__map *, const char*);
SOAP_FMAC3 ZQ2__map * SOAP_FMAC4 soap_get_ZQ2__map(struct soap*, ZQ2__map *, const char*, const char*);
SOAP_FMAC3 ZQ2__map * SOAP_FMAC4 soap_in_ZQ2__map(struct soap*, const char*, ZQ2__map *, const char*);
SOAP_FMAC5 ZQ2__map * SOAP_FMAC6 soap_new_ZQ2__map(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__map(struct soap*, ZQ2__map*);
SOAP_FMAC3 ZQ2__map * SOAP_FMAC4 soap_instantiate_ZQ2__map(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__map(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__pair
#define SOAP_TYPE_ZQ2__pair (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__pair(struct soap*, const char*, int, const ZQ2__pair *, const char*);
SOAP_FMAC3 ZQ2__pair * SOAP_FMAC4 soap_get_ZQ2__pair(struct soap*, ZQ2__pair *, const char*, const char*);
SOAP_FMAC3 ZQ2__pair * SOAP_FMAC4 soap_in_ZQ2__pair(struct soap*, const char*, ZQ2__pair *, const char*);
SOAP_FMAC5 ZQ2__pair * SOAP_FMAC6 soap_new_ZQ2__pair(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__pair(struct soap*, ZQ2__pair*);
SOAP_FMAC3 ZQ2__pair * SOAP_FMAC4 soap_instantiate_ZQ2__pair(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__pair(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsdl__State
#define SOAP_TYPE_wsdl__State (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsdl__State(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsdl__State(struct soap*, std::string const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsdl__State(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsdl__State(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_wsdl__State(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_wsdl__State(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_wsdl__State(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_wsdl__State(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_wsdl__State(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsdl__State(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ZQ2__notifyStatus
#define SOAP_TYPE_ZQ2__notifyStatus (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__notifyStatus(struct soap*, struct ZQ2__notifyStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__notifyStatus(struct soap*, const struct ZQ2__notifyStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__notifyStatus(struct soap*, const struct ZQ2__notifyStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__notifyStatus(struct soap*, const char*, int, const struct ZQ2__notifyStatus *, const char*);
SOAP_FMAC3 struct ZQ2__notifyStatus * SOAP_FMAC4 soap_get_ZQ2__notifyStatus(struct soap*, struct ZQ2__notifyStatus *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__notifyStatus * SOAP_FMAC4 soap_in_ZQ2__notifyStatus(struct soap*, const char*, struct ZQ2__notifyStatus *, const char*);
SOAP_FMAC5 struct ZQ2__notifyStatus * SOAP_FMAC6 soap_new_ZQ2__notifyStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__notifyStatus(struct soap*, struct ZQ2__notifyStatus*);
SOAP_FMAC3 struct ZQ2__notifyStatus * SOAP_FMAC4 soap_instantiate_ZQ2__notifyStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__notifyStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__notifyStatusResponse
#define SOAP_TYPE_ZQ2__notifyStatusResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__notifyStatusResponse(struct soap*, struct ZQ2__notifyStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__notifyStatusResponse(struct soap*, const struct ZQ2__notifyStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__notifyStatusResponse(struct soap*, const struct ZQ2__notifyStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__notifyStatusResponse(struct soap*, const char*, int, const struct ZQ2__notifyStatusResponse *, const char*);
SOAP_FMAC3 struct ZQ2__notifyStatusResponse * SOAP_FMAC4 soap_get_ZQ2__notifyStatusResponse(struct soap*, struct ZQ2__notifyStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__notifyStatusResponse * SOAP_FMAC4 soap_in_ZQ2__notifyStatusResponse(struct soap*, const char*, struct ZQ2__notifyStatusResponse *, const char*);
SOAP_FMAC5 struct ZQ2__notifyStatusResponse * SOAP_FMAC6 soap_new_ZQ2__notifyStatusResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__notifyStatusResponse(struct soap*, struct ZQ2__notifyStatusResponse*);
SOAP_FMAC3 struct ZQ2__notifyStatusResponse * SOAP_FMAC4 soap_instantiate_ZQ2__notifyStatusResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__notifyStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__getStatus
#define SOAP_TYPE_ZQ2__getStatus (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__getStatus(struct soap*, struct ZQ2__getStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__getStatus(struct soap*, const struct ZQ2__getStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__getStatus(struct soap*, const struct ZQ2__getStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__getStatus(struct soap*, const char*, int, const struct ZQ2__getStatus *, const char*);
SOAP_FMAC3 struct ZQ2__getStatus * SOAP_FMAC4 soap_get_ZQ2__getStatus(struct soap*, struct ZQ2__getStatus *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__getStatus * SOAP_FMAC4 soap_in_ZQ2__getStatus(struct soap*, const char*, struct ZQ2__getStatus *, const char*);
SOAP_FMAC5 struct ZQ2__getStatus * SOAP_FMAC6 soap_new_ZQ2__getStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__getStatus(struct soap*, struct ZQ2__getStatus*);
SOAP_FMAC3 struct ZQ2__getStatus * SOAP_FMAC4 soap_instantiate_ZQ2__getStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__getStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__getStatusResponse
#define SOAP_TYPE_ZQ2__getStatusResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__getStatusResponse(struct soap*, struct ZQ2__getStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__getStatusResponse(struct soap*, const struct ZQ2__getStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__getStatusResponse(struct soap*, const struct ZQ2__getStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__getStatusResponse(struct soap*, const char*, int, const struct ZQ2__getStatusResponse *, const char*);
SOAP_FMAC3 struct ZQ2__getStatusResponse * SOAP_FMAC4 soap_get_ZQ2__getStatusResponse(struct soap*, struct ZQ2__getStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__getStatusResponse * SOAP_FMAC4 soap_in_ZQ2__getStatusResponse(struct soap*, const char*, struct ZQ2__getStatusResponse *, const char*);
SOAP_FMAC5 struct ZQ2__getStatusResponse * SOAP_FMAC6 soap_new_ZQ2__getStatusResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__getStatusResponse(struct soap*, struct ZQ2__getStatusResponse*);
SOAP_FMAC3 struct ZQ2__getStatusResponse * SOAP_FMAC4 soap_instantiate_ZQ2__getStatusResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__getStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__teardown
#define SOAP_TYPE_ZQ2__teardown (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__teardown(struct soap*, struct ZQ2__teardown *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__teardown(struct soap*, const struct ZQ2__teardown *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__teardown(struct soap*, const struct ZQ2__teardown *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__teardown(struct soap*, const char*, int, const struct ZQ2__teardown *, const char*);
SOAP_FMAC3 struct ZQ2__teardown * SOAP_FMAC4 soap_get_ZQ2__teardown(struct soap*, struct ZQ2__teardown *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__teardown * SOAP_FMAC4 soap_in_ZQ2__teardown(struct soap*, const char*, struct ZQ2__teardown *, const char*);
SOAP_FMAC5 struct ZQ2__teardown * SOAP_FMAC6 soap_new_ZQ2__teardown(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__teardown(struct soap*, struct ZQ2__teardown*);
SOAP_FMAC3 struct ZQ2__teardown * SOAP_FMAC4 soap_instantiate_ZQ2__teardown(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__teardown(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__teardownResponse
#define SOAP_TYPE_ZQ2__teardownResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__teardownResponse(struct soap*, struct ZQ2__teardownResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__teardownResponse(struct soap*, const struct ZQ2__teardownResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__teardownResponse(struct soap*, const struct ZQ2__teardownResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__teardownResponse(struct soap*, const char*, int, const struct ZQ2__teardownResponse *, const char*);
SOAP_FMAC3 struct ZQ2__teardownResponse * SOAP_FMAC4 soap_get_ZQ2__teardownResponse(struct soap*, struct ZQ2__teardownResponse *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__teardownResponse * SOAP_FMAC4 soap_in_ZQ2__teardownResponse(struct soap*, const char*, struct ZQ2__teardownResponse *, const char*);
SOAP_FMAC5 struct ZQ2__teardownResponse * SOAP_FMAC6 soap_new_ZQ2__teardownResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__teardownResponse(struct soap*, struct ZQ2__teardownResponse*);
SOAP_FMAC3 struct ZQ2__teardownResponse * SOAP_FMAC4 soap_instantiate_ZQ2__teardownResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__teardownResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__setup
#define SOAP_TYPE_ZQ2__setup (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__setup(struct soap*, struct ZQ2__setup *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__setup(struct soap*, const struct ZQ2__setup *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__setup(struct soap*, const struct ZQ2__setup *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__setup(struct soap*, const char*, int, const struct ZQ2__setup *, const char*);
SOAP_FMAC3 struct ZQ2__setup * SOAP_FMAC4 soap_get_ZQ2__setup(struct soap*, struct ZQ2__setup *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__setup * SOAP_FMAC4 soap_in_ZQ2__setup(struct soap*, const char*, struct ZQ2__setup *, const char*);
SOAP_FMAC5 struct ZQ2__setup * SOAP_FMAC6 soap_new_ZQ2__setup(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__setup(struct soap*, struct ZQ2__setup*);
SOAP_FMAC3 struct ZQ2__setup * SOAP_FMAC4 soap_instantiate_ZQ2__setup(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__setup(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ZQ2__setupResponse
#define SOAP_TYPE_ZQ2__setupResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ZQ2__setupResponse(struct soap*, struct ZQ2__setupResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ZQ2__setupResponse(struct soap*, const struct ZQ2__setupResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ZQ2__setupResponse(struct soap*, const struct ZQ2__setupResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ZQ2__setupResponse(struct soap*, const char*, int, const struct ZQ2__setupResponse *, const char*);
SOAP_FMAC3 struct ZQ2__setupResponse * SOAP_FMAC4 soap_get_ZQ2__setupResponse(struct soap*, struct ZQ2__setupResponse *, const char*, const char*);
SOAP_FMAC3 struct ZQ2__setupResponse * SOAP_FMAC4 soap_in_ZQ2__setupResponse(struct soap*, const char*, struct ZQ2__setupResponse *, const char*);
SOAP_FMAC5 struct ZQ2__setupResponse * SOAP_FMAC6 soap_new_ZQ2__setupResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ZQ2__setupResponse(struct soap*, struct ZQ2__setupResponse*);
SOAP_FMAC3 struct ZQ2__setupResponse * SOAP_FMAC4 soap_instantiate_ZQ2__setupResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ZQ2__setupResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToZQ2__setupInfo
#define SOAP_TYPE_PointerToZQ2__setupInfo (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToZQ2__setupInfo(struct soap*, ZQ2__setupInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToZQ2__setupInfo(struct soap*, ZQ2__setupInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToZQ2__setupInfo(struct soap*, const char *, int, ZQ2__setupInfo *const*, const char *);
SOAP_FMAC3 ZQ2__setupInfo ** SOAP_FMAC4 soap_get_PointerToZQ2__setupInfo(struct soap*, ZQ2__setupInfo **, const char*, const char*);
SOAP_FMAC3 ZQ2__setupInfo ** SOAP_FMAC4 soap_in_PointerToZQ2__setupInfo(struct soap*, const char*, ZQ2__setupInfo **, const char*);

#ifndef SOAP_TYPE_PointerToZQ2__map
#define SOAP_TYPE_PointerToZQ2__map (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToZQ2__map(struct soap*, ZQ2__map *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToZQ2__map(struct soap*, ZQ2__map *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToZQ2__map(struct soap*, const char *, int, ZQ2__map *const*, const char *);
SOAP_FMAC3 ZQ2__map ** SOAP_FMAC4 soap_get_PointerToZQ2__map(struct soap*, ZQ2__map **, const char*, const char*);
SOAP_FMAC3 ZQ2__map ** SOAP_FMAC4 soap_in_PointerToZQ2__map(struct soap*, const char*, ZQ2__map **, const char*);

#ifndef SOAP_TYPE_PointerToZQ2__pair
#define SOAP_TYPE_PointerToZQ2__pair (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToZQ2__pair(struct soap*, ZQ2__pair *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToZQ2__pair(struct soap*, ZQ2__pair *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToZQ2__pair(struct soap*, const char *, int, ZQ2__pair *const*, const char *);
SOAP_FMAC3 ZQ2__pair ** SOAP_FMAC4 soap_get_PointerToZQ2__pair(struct soap*, ZQ2__pair **, const char*, const char*);
SOAP_FMAC3 ZQ2__pair ** SOAP_FMAC4 soap_in_PointerToZQ2__pair(struct soap*, const char*, ZQ2__pair **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerToZQ2__pair
#define SOAP_TYPE_std__vectorTemplateOfPointerToZQ2__pair (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, std::vector<ZQ2__pair * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, const std::vector<ZQ2__pair * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, const char*, int, const std::vector<ZQ2__pair * >*, const char*);
SOAP_FMAC3 std::vector<ZQ2__pair * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, const char*, std::vector<ZQ2__pair * >*, const char*);
SOAP_FMAC5 std::vector<ZQ2__pair * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, std::vector<ZQ2__pair * >*);
SOAP_FMAC3 std::vector<ZQ2__pair * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerToZQ2__pair(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
