[ ] //------------------------------------------------------------------------------
[ ] //111111102222222220333333333044444444405555555550666666666077777777708888888880
[ ] // Filename:    aquariusmsgs.inc
[ ] // Project:     Aquarius
[ ] // Author:		CAC
[ ] // Description: Defines Aquarius specific error and generic message strings 
[ ] // Created On:  12/13/2002
[ ] 
[ ] // Significant revisions:
[ ] // mm/dd/yyyy FML Revision Comment
[ ] //------------------------------------------------------------------------------
