#ifndef _VVXDEF_H
#define _VVXDEF_H
//
// this file was created based on the vvx file created using the default compilation flags
// for NT which adds filler data preceding certain fields based on the natural alignment of
// the field (8, 16, 32 or 64 bits and the current structure alignment).  
//
// Other compilers may choose to pad the structures using a different set of rules which makes 
// producing compatable index files problematic, hence this file gives the byte offset of 
// each element in the structure which then can be used to produce compatible index files.
//
#ifdef __cplusplus
extern "C" {
#endif

#define SETLONGLONG(a,b)	(*(PULONGLONG)(a)		= (UINT64)(b))
#define SETLONG(a,b)		(*(PULONG)(a)			= (ULONG)(b))
#define SETSHORT(a,b)		(*(PUSHORT)(a)			= (USHORT)(b))
#define SETCHAR(a,b)		(*(PBYTE)(a)			= (BYTE)(b))
	
#define GETLONGLONG(a)		(*(PULONGLONG)(a))
#define GETLONG(a)			(*(PULONG)(a))
#define GETSHORT(a)			(*(PUSHORT)(a))
#define GETCHAR(a)			(*(PBYTE)(a))
//
// index header (VVX_V7_INDEX_HEADER)
//
#define VVX_V7IH_SIGNATURE_OFFSET 					0
#define VVX_V7IH_SIGNATURE_SIZE 					32
#define VVX_V7IH_HEADERLENGTH_OFFSET 				32 
#define VVX_V7IH_HEADERLENGTH_SIZE 					4
#define VVX_V7IH_MAJORVERSION_OFFSET 				36 
#define VVX_V7IH_MAJORVERSION_SIZE 					2
#define VVX_V7IH_MINORVERSION_OFFSET 				38 
#define VVX_V7IH_MINORVERSION_SIZE 					2
#define VVX_V7IH_PROGRAMVERSION_OFFSET 				40 
#define VVX_V7IH_PROGRAMVERSION_SIZE 				256
#define VVX_V7IH_FILENAME_OFFSET 					296 
#define VVX_V7IH_FILENAME_SIZE 						256
#define VVX_V7IH_SYSTEMTIME_OFFSET 					552 
#define VVX_V7IH_SYSTEMTIME_SIZE 					8
#define VVX_V7IH_STREAMBITRATE_OFFSET 				560 
#define VVX_V7IH_STREAMBITRATE_SIZE 				4
#define VVX_V7IH_STREAMTYPE_OFFSET 					564 
#define VVX_V7IH_STREAMTYPE_SIZE 					4

#define VVX_V7IH_TSINFORMATIONCOUNT_OFFSET 			568 
#define VVX_V7IH_TSINFORMATIONCOUNT_SIZE 			4
#define VVX_V7IH_TSINFORMATIONLENGTH_OFFSET 		572 
#define VVX_V7IH_TSINFORMATIONLENGTH_SIZE 			4
#define VVX_V7IH_TSINFORMATIONOFFSET_OFFSET 		576 
#define VVX_V7IH_TSINFORMATIONOFFSET_SIZE 			4

#define VVX_V7IH_TRICKINDEXRECORDCOUNT_OFFSET 		580 
#define VVX_V7IH_TRICKINDEXRECORDCOUNT_SIZE 		4
#define VVX_V7IH_SPLICEINDEXRECORDCOUNT_OFFSET 		584 
#define VVX_V7IH_SPLICEINDEXRECORDCOUNT_SIZE 		4

#define VVX_V7IH_ESINFORMATIONCOUNT_OFFSET 			588 
#define VVX_V7IH_ESINFORMATIONCOUNT_SIZE 			4
#define VVX_V7IH_ESINFORMATIONLENGTH_OFFSET 		592 
#define VVX_V7IH_ESINFORMATIONLENGTH_SIZE 			4
#define VVX_V7IH_ESINFORMATIONOFFSET_OFFSET 		596 
#define VVX_V7IH_ESINFORMATIONOFFSET_SIZE 			4

#define VVX_V7IH_SUBFILEINFORMATIONMAXCOUNT_OFFSET 	600 
#define VVX_V7IH_SUBFILEINFORMATIONMAXCOUNT_SIZE 	4
#define VVX_V7IH_SUBFILEINFORMATIONCOUNT_OFFSET 	604 
#define VVX_V7IH_SUBFILEINFORMATIONCOUNT_SIZE 		4
#define VVX_V7IH_SUBFILEINFORMATIONLENGTH_OFFSET 	608 
#define VVX_V7IH_SUBFILEINFORMATIONLENGTH_SIZE 		4
#define VVX_V7IH_SUBFILEINFORMATIONOFFSET_OFFSET 	612 
#define VVX_V7IH_SUBFILEINFORMATIONOFFSET_SIZE 		4

#define VVX_V7IH_FRAMERATECODE_OFFSET 				616 
#define VVX_V7IH_FRAMERATECODE_SIZE 				4
#define VVX_V7IH_DTSPTSTIMEOFFSET_OFFSET 			624 
#define VVX_V7IH_DTSPTSTIMEOFFSET_SIZE 				8
#define VVX_V7IH_HORIZONTALSIZE_OFFSET 				632 
#define VVX_V7IH_HORIZONTALSIZE_SIZE 				4
#define VVX_V7IH_VERTICALSIZE_OFFSET 				636 
#define VVX_V7IH_VERTICALSIZE_SIZE 					4
#define VVX_V7IH_VIDEOBITRATE_OFFSET 				640 
#define VVX_V7IH_VIDEOBITRATE_SIZE 					4

#define VVX_V7IH_ZEROMOTIONPICTURETYPE_OFFSET 		644 
#define VVX_V7IH_ZEROMOTIONPICTURETYPE_SIZE 		4
#define VVX_V7IH_ZEROMOTIONBFRAMEPESOFFSET_OFFSET 	648 
#define VVX_V7IH_ZEROMOTIONBFRAMEPESOFFSET_SIZE 	4
#define VVX_V7IH_ZEROMOTIONBFRAMEPESLENGTH_OFFSET 	652 
#define VVX_V7IH_ZEROMOTIONBFRAMEPESLENGTH_SIZE 	4

#define VVX_V7IH_ZEROMOTIONFRAMEPESOFFSET_OFFSET 	656 
#define VVX_V7IH_ZEROMOTIONFRAMEPESOFFSET_SIZE 		4
#define VVX_V7IH_ZEROMOTIONFRAMEPESLENGTH_OFFSET 	660 
#define VVX_V7IH_ZEROMOTIONFRAMEPESLENGTH_SIZE 		4

#define VVX_V7IH_FRAMEDATACOUNT_OFFSET 				664 
#define VVX_V7IH_FRAMEDATACOUNT_SIZE 				4
#define VVX_V7IH_FRAMEDATAOFFSET_OFFSET 			668 
#define VVX_V7IH_FRAMEDATAOFFSET_SIZE 				4
#define VVX_V7IH_FRAMEDATALENGTH_OFFSET 			672 
#define VVX_V7IH_FRAMEDATALENGTH_SIZE 				4

#define VVX_V7IH_ESDESCRIPTORDATACOUNT_OFFSET 		676 
#define VVX_V7IH_ESDESCRIPTORDATACOUNT_SIZE 		4
#define VVX_V7IH_ESDESCRIPTORDATALENGTH_OFFSET 		680 
#define VVX_V7IH_ESDESCRIPTORDATALENGTH_SIZE 		4
#define VVX_V7IH_ESDESCRIPTORDATAOFFSET_OFFSET 		684 
#define VVX_V7IH_ESDESCRIPTORDATAOFFSET_SIZE 		4

#define VVX_V7IH_EXTENDEDHEADERLENGTH_OFFSET 		688 
#define VVX_V7IH_EXTENDEDHEADERLENGTH_SIZE 			4

#define VVX_V7IH_REVERSEREAD_OFFSET 				692 
#define VVX_V7IH_REVERSEREAD_SIZE 					1
#define VVX_V7IH_USEPRIVATEDATA_OFFSET 				693 
#define VVX_V7IH_USEPRIVATEDATA_SIZE 				1
#define VVX_V7IH_AVAILABLE_BOOLEAN_1_OFFSET 		693 
#define VVX_V7IH_AVAILABLE_BOOLEAN_1_SIZE 			1
#define VVX_V7IH_AVAILABLE_BOOLEAN_OFFSET 			695 
#define VVX_V7IH_AVAILABLE_BOOLEAN_SIZE 			1

#define VVX_V7IH_SPLICINGPARAMETERSLENGTH_OFFSET 	696 
#define VVX_V7IH_SPLICINGPARAMETERSLENGTH_SIZE 		4
#define VVX_V7IH_SPLICINGPARAMETERSOFFSET_OFFSET 	700 
#define VVX_V7IH_SPLICINGPARAMETERSOFFSET_SIZE 		4

#define VVX_V7IH_CHECKSUMREF_OFFSET 				704 
#define VVX_V7IH_CHECKSUMREF_SIZE 					4
#define VVX_V7IH_SIZE 								712
//
// subfile information (VVX_SUBFILE_INFORMATION)
//
#define VVX_V7SI_FILEEXTENSION_OFFSET 				0 
#define VVX_V7SI_FILEEXTENSION_SIZE 				8
#define VVX_V7SI_FILETYPE_OFFSET 					8 
#define VVX_V7SI_FILETYPE_SIZE 						4
#define VVX_V7SI_STARTINGBYTE_OFFSET 				16 
#define VVX_V7SI_STARTINGBYTE_SIZE 					8
#define VVX_V7SI_ENDINGBYTE_OFFSET 					24 
#define VVX_V7SI_ENDINGBYTE_SIZE 					8
#define VVX_V7SI_PLAYTIMEINMILLISECONDS_OFFSET 		32 
#define VVX_V7SI_PLAYTIMEINMILLISECONDS_SIZE 		4
#define VVX_V7SI_SPEED_NUMERATOR_OFFSET 			36 
#define VVX_V7SI_SPEED_NUMERATOR_SIZE 				4
#define VVX_V7SI_SPEED_DENOMINATOR_OFFSET 			40 
#define VVX_V7SI_SPEED_DENOMINATOR_SIZE 			4
#define VVX_V7SI_RECORDINDEX_OFFSET 				44 
#define VVX_V7SI_RECORDINDEX_SIZE 					4
#define VVX_V7SI_SIZE 								48
//
// transport stream information (VVX_TS_INFORMATION)
//
#define VVX_V7TI_PROGRAMNUMBER_OFFSET 				0 
#define VVX_V7TI_PROGRAMNUMBER_SIZE 				4
#define VVX_V7TI_PMTPID_OFFSET 						4 
#define VVX_V7TI_PMTPID_SIZE 						4
#define VVX_V7TI_PCRPID_OFFSET 						8 
#define VVX_V7TI_PCRPID_SIZE 						4
#define VVX_V7TI_VIDEOPID_OFFSET 					12 
#define VVX_V7TI_VIDEOPID_SIZE 						4
#define VVX_V7TI_SIZE								16
//
// elementary stream information (VVX_ES_INFORMATION)
//
#define VVX_V7EI_STREAMTYPE_OFFSET 					0 
#define VVX_V7EI_STREAMTYPE_SIZE 					1
#define VVX_V7EI_STREAMFLAGS_OFFSET 				1 
#define VVX_V7EI_STREAMFLAGS_SIZE 					1
#define VVX_V7EI_PID_OFFSET 						2 
#define VVX_V7EI_PID_SIZE 							2
#define VVX_V7EI_SIZE 								4
//
// stream descriptor data (VVX_ES_DESCRIPTOR_DATA)
//
#define VVX_V7DD_DESCRIPTORDATALENGTH_OFFSET 		0 
#define VVX_V7DD_DESCRIPTORDATALENGTH_SIZE 			4
#define VVX_V7DD_DESCRIPTORDATAOFFSET_OFFSET 		4 
#define VVX_V7DD_DESCRIPTORDATAOFFSET_OFFSET_SIZE 	4
#define VVX_V7DD_SIZE 								8
//
// index record layout (VVX_V7_RECORD)
//
// type field (8 bytes)
#define VVX_V7R_RECORDTYPE_OFFSET					0 
#define VVX_V7R_RECORDTYPE_SIZE						4
// trick entry (16 bytes)
#define VVX_V7R_TRICK_TIMECODE_OFFSET				8 
#define VVX_V7R_TRICK_TIMECODE_SIZE					4
#define VVX_V7R_TRICK_TIMECODE_HOURS_OFFSET			8 
#define VVX_V7R_TRICK_TIMECODE_HOURS_SIZE			1
#define VVX_V7R_TRICK_TIMECODE_MINUTES_OFFSET		9 
#define VVX_V7R_TRICK_TIMECODE_MINUTES_SIZE			1
#define VVX_V7R_TRICK_TIMECODE_SECONDS_OFFSET		10 
#define VVX_V7R_TRICK_TIMECODE_SECONDS_SIZE			1
#define VVX_V7R_TRICK_TIMECODE_FRAMES_OFFSET		11 
#define VVX_V7R_TRICK_TIMECODE_FRAMES_SIZE			1
#define VVX_V7R_TRICK_FRAMEBYTEOFFSET_OFFSET		16 
#define VVX_V7R_TRICK_FRAMEBYTEOFFSET_SIZE			8
// splice entry (56 bytes)
#define VVX_V7R_SPLICE_TYPE_OFFSET					8
#define VVX_V7R_SPLICE_TYPE_SIZE					2
#define VVX_V7R_SPLICE_ID_OFFSET					16
#define VVX_V7R_SPLICE_ID_SIZE						8
#define VVX_V7R_SPLICE_TIMEOFFSET_OFFSET			24
#define VVX_V7R_SPLICE_TIMEOFFSET_SIZE				8
#define VVX_V7R_SPLICE_SOURCEFILEOFFSET_OFFSET		32
#define VVX_V7R_SPLICE_SOURCEFILEOFFSET_SIZE		8
#define VVX_V7R_SPLICE_SPLICEFILEOFFSET_OFFSET		40
#define VVX_V7R_SPLICE_SPLICEFILEOFFSET_SIZE		8
#define VVX_V7R_SPLICE_SPLICESEGMENTLENGTH_OFFSET	48
#define VVX_V7R_SPLICE_SPLICESEGMENTLENGTH_SIZE		8
#define VVX_V7R_SPLICE_SUBFILEBYTEOFFSET_OFFSET		56
#define VVX_V7R_SPLICE_SUBFILEBYTEOFFSET_SIZE		8
#define VVX_V7R_SPLICE_TRICKINDEXOFSPLICE_OFFSET	56
#define VVX_V7R_SPLICE_TRICKINDEXOFSPLICE_SIZE		4

#define VVX_V7R_SIZE								136 

#ifdef __cplusplus
}
#endif

#endif // _VVXDEF_H

