@echo off

setlocal

set path=%ProgramFiles%\doxygen\bin;%ZQProjsPath%\build\utils;%path%
set HHC="%ProgramFiles%\HTML Help Workshop\hhc.exe"
set PUBLISHLOC=\\192.168.80.49\d$\wpub\engineering

for %%d in (html latex rtf ext1) do rd /s /q %%d

if .%1. == .FULL. goto full_loc
if .%1. == .PROD. goto prod_loc
if .%1. == .SDK.  goto sdk_loc

if NOT .%1. == .. goto quit_loc

:sdk_loc

sed -f ..\..\build\DoxClean.sed ..\..\build\template.dox > temp.dox
echo.>> temp.dox
echo #--------------------------------------------------------------------------->> temp.dox
echo # Configuration::additions generated by script   >> temp.dox
echo #--------------------------------------------------------------------------->> temp.dox
echo PROJECT_NAME="TianShan Architecture SDK" >> temp.dox
echo INPUT=..\ICE .\TianShanSDK.dxm >> temp.dox
echo FILE_PATTERNS= *.ICE *.xmp >> temp.dox
echo INPUT_FILTER= "sed -f ../../build/Ice4Dox.sed " >> temp.dox
echo RECURSIVE=NO >> temp.dox
echo IMAGE_PATH=..\doc\images >> temp.dox
echo WARN_LOGFILE=TianShanSDK.log >> temp.dox
echo HHC_LOCATION=%HHC% >> temp.dox
echo CHM_FILE=..\TianShanSDK.chm >> temp.dox
echo HTML_FOOTER=./doxfooter.txt >> temp.dox

del /f TianShanSDK.chm
mkdir html
copy images\logo*.* html\
doxygen.exe temp.dox
if exist %PUBLISHLOC%\TianShan\html rd/s/q %PUBLISHLOC%\TianShan\html & xcopy /IEF html %PUBLISHLOC%\TianShan\html
for %%d in (html latex rtf) do if exist %%d rd /s /q %%d

if NOT .%1. == .. goto quit_loc

:prod_loc

sed -f ..\..\build\DoxClean.sed ..\..\build\template.dox > temp.dox
echo.>> temp.dox
echo #--------------------------------------------------------------------------->> temp.dox
echo # Configuration::additions generated by script   >> temp.dox
echo #--------------------------------------------------------------------------->> temp.dox
echo PROJECT_NAME="ZQ TianShan Products" >> temp.dox
echo INPUT=. .\TianShanZQ.dxm ..\ICE >> temp.dox
echo IMAGE_PATH=..\doc\images >> temp.dox
echo FILE_PATTERNS= *.dxd *.xmp *.dxc >> temp.dox
echo INPUT_FILTER= "sed -f ../../build/Ice4Dox.sed " >> temp.dox
echo RECURSIVE=NO >> temp.dox
echo WARN_LOGFILE=TsZQProd.log >> temp.dox
echo HHC_LOCATION=%HHC% >> temp.dox
echo CHM_FILE=..\TsZQProd.chm >> temp.dox
echo HTML_FOOTER=./doxfooter.txt >> temp.dox

del /f TsZQProd.chm
mkdir html
copy images\logo*.* html\
doxygen.exe temp.dox

if NOT .%1. == .. goto quit_loc

:full_loc

sed -f ..\..\build\DoxClean.sed ..\..\build\template.dox > temp.dox
echo.>> temp.dox
echo #--------------------------------------------------------------------------->> temp.dox
echo # Configuration::additions generated by script   >> temp.dox
echo #--------------------------------------------------------------------------->> temp.dox
echo PROJECT_NAME="TianShan Architecture (ZQ)" >> temp.dox
echo INPUT=. .\TianShanZQ.dxm ..\common\TsLayout.h ..\StreamSmith\StreamSmithModule.h ..\ICE >> temp.dox
echo IMAGE_PATH=..\doc\images >> temp.dox
echo FILE_PATTERNS= *.dxd *.ICE *.xmp *.dxc >> temp.dox
echo INPUT_FILTER= "sed -f ../../build/Ice4Dox.sed " >> temp.dox
echo RECURSIVE=NO >> temp.dox
echo WARN_LOGFILE=TsZQFull.log >> temp.dox
echo HHC_LOCATION=%HHC% >> temp.dox
echo CHM_FILE=..\TsZQFull.chm >> temp.dox
echo HTML_FOOTER=./doxfooter.txt >> temp.dox

del /f TsZQFull.chm
mkdir html
copy images\logo*.* html\
doxygen.exe temp.dox

:quit_loc

rem rd /s /q html latex arch impl

endlocal
