mkdir -p  ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2cpp  ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/ngod.ice  -I ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod -I ${ZQProjsPath}/TianShan/Ice  -I ${ICE_ROOT}/slice   --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2cpp  ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/LAMFacade.ice -I ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice -I ${ICE_ROOT}/slice/Ice -I ${ZQProjsPath}/TianShan/MetaLib   --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2cpp  ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/StreamSmithAdmin.ICE  -I ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod -I ${ZQProjsPath}/TianShan/Ice  -I ${ICE_ROOT}/slice -I ${ZQProjsPath}/TianShan/MetaLib   --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2cpp  ${ZQProjsPath}/TianShan/MetaLib/MetaLib.ICE  -I ${ZQProjsPath}/TianShan/Ice -I ${ICE_ROOT}/slice -I ${ZQProjsPath}/TianShan/MetaLib   --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2cpp  ${ZQProjsPath}/TianShan/ContentLib/ContentReplicaEx.ICE   -I ${ZQProjsPath}/TianShan/Ice  -I ${ICE_ROOT}/slice -I ${ICE_ROOT}/slice -I ${ZQProjsPath}/TianShan/ContentLib -I ${ZQProjsPath}/TianShan/MetaLib   --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod  -I ${ZQProjsPath}/TianShan/Ice -I ${ZQProjsPath}/TianShan/common  -I ${ICE_ROOT}/slice   --index "NGOD::StreamIdx,NGOD::NgodSession,mStreamSessId" StreamIdx  ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/ngod.ice --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod  -I ${ZQProjsPath}/TianShan/Ice -I ${ZQProjsPath}/TianShan/common -I ${ICE_ROOT}/slice   --index "NGOD::GroupIdx,NGOD::NgodSession,mGroupId" GroupIdx ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/ngod.ice --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
${SYS_INTERP} --library-path ${ICE_ROOT}/lib ${ICE_ROOT}/bin/slice2freeze -I ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod  -I ${ZQProjsPath}/TianShan/Ice -I ${ZQProjsPath}/TianShan/common  -I ${ICE_ROOT}/slice   --index "NGOD::Streamer2Sess,NGOD::NgodSession,mStreamerNetId" Streamer2Sess  ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/ngod.ice --output-dir ${ZQProjsPath}/TianShan/ComcastNGOD/ssm_ngod/Ice
