TOPDIR := ../../../

include $(TOPDIR)/build/defines.mk

SOLIB := CPEMan_web

OBJS := BasePage.os CpeMan_web.os MethodController.os SessionController.os  stroprt.os  

include $(TOPDIR)/build/common.mk

LDFLAGS += $(commonlink) $(icelink) 


