TOPDIR := ../../../..

include $(TOPDIR)/build/defines.mk

SOLIB := MsgSender

OBJS := BaseSender.os ConfigHelper.os IceSender.os MagSender.os MsgSender.os TextWriter.os 

INCDIR += ../../EventSink   

LDFLAGS += $(commonlink) $(icelink) 

include $(TOPDIR)/build/common.mk




